export interface LEDBillboard {
  id: string;
  type: 'led';
  district: string;
  name: string;
  address: string;
  nickname: string | null;
  neighborhood: string;
  period: string;
  price: string;
  size: string;
  faces: number;
  latitude: number;
  longitude: number;
  photo_url?: string | null;
  status: string;
  panel_width: number;
  panel_height: number;
  panel_code: number;
  panel_type: string;
  exposure_count: number;
  max_banners: number;
  slot_width_px: number;
  slot_height_px: number;
  total_price: number;
  tax_price: number;
  advertising_fee: number;
  road_usage_fee: number;
  administrative_fee: number;
  price_unit: string;
  panel_slot_status: string;
  panel_id?: string;
}
