import DigitalSignageDetailClient from './DigitalSignageDetailClient';

// 제품 데이터 타입 정의
interface ProductData {
  id: string;
  title: string;
  image: string;
  images?: string[];
  modelName?: string;
  pixelPitchOptions?: string[];
  specifications?: {
    operatingLineup?: string;
    modelName?: string;
    productSize?: string;
    resolutionBrightness?: string;
    keyFeatures?: string;
    usage?: string;
    installationMethod?: string;
    inquiry?: string;
    moduleSize?: string;
    moduleResolution?: string;
    pixelDensity?: string;
    optimalViewingDistance?: string;
    screenBrightness?: string;
    pixelConfiguration?: string;
    refreshRate?: string;
    viewingAngle?: string;
    flatness?: string;
    operatingTemperature?: string;
    operatingHumidity?: string;
    ratedInput?: string;
    maintenance?: string;
  };
  description?: string;
  type?: string;
  models?: {
    [key: string]: Array<{
      modelName: string;
      resolution: string;
      brightness: string;
      size: string;
      vesaHole: string;
      price: string;
      stock?: string;
      brand?: string;
      inch?: string;
    }>;
  };
}

// 제품 데이터 매핑
const productDataMap: Record<string, ProductData> = {
  // 미디어경관디자인
  'gansong-art-museum': {
    id: 'gansong-art-museum',
    title: '간송미술관',
    image:
      '/images/digital-sianage/media_display/간송미술관/2025_간송미술관-무기명_1.jpg',
    images: [
      '/images/digital-sianage/media_display/간송미술관/2025_간송미술관-무기명_1.jpg',
      '/images/digital-sianage/media_display/간송미술관/2025_간송미술관-무기명_2.jpg',
      '/images/digital-sianage/media_display/간송미술관/2025_간송미술관-무기명_3.jpg',
      '/images/digital-sianage/media_display/간송미술관/2025_간송미술관-무기명_4.jpg',
      '/images/digital-sianage/media_display/간송미술관/2025_간송미술관-무기명_5.jpg',
    ],
    specifications: {
      operatingLineup: '문화시설 전용 디스플레이',
      modelName: '간송미술관 미디어 디스플레이',
      productSize: '상세페이지 참조',
      resolutionBrightness: '고해상도 디스플레이 / 최적화된 밝기',
      keyFeatures: '문화시설 맞춤형 디스플레이 / 예술작품 전시 최적화',
      usage: '미술관 전시, 문화 콘텐츠 송출, 관람객 안내',
      installationMethod: '전시공간 맞춤 설치, 조명 연동',
      inquiry: '1833-9009',
    },
  },
  'red-road': {
    id: 'red-road',
    title: '레드로드',
    image:
      '/images/digital-sianage/media_display/레드로드/홍대 전광판 제안서_1.jpg',
    images: [
      '/images/digital-sianage/media_display/레드로드/홍대 전광판 제안서_1.jpg',
      '/images/digital-sianage/media_display/레드로드/홍대 전광판 제안서_3.jpg',
      '/images/digital-sianage/media_display/레드로드/홍대 전광판 제안서_4.jpg',
      '/images/digital-sianage/media_display/레드로드/홍대 전광판 제안서_5.jpg',
    ],
    specifications: {
      operatingLineup: '홍대 지역 전용 전광판',
      modelName: '홍대 레드로드 전광판',
      productSize: '상세페이지 참조',
      resolutionBrightness: '고휘도 디스플레이 / 야외 환경 최적화',
      keyFeatures: '홍대 지역 특화 디스플레이 / 젊은 문화 콘텐츠',
      usage: '홍대 지역 광고, 문화 이벤트, 지역 정보 안내',
      installationMethod: '야외 전광판 설치, 방수/방진 처리',
      inquiry: '1833-9009',
    },
  },
  'baengnyeon-market': {
    id: 'baengnyeon-market',
    title: '백년시장',
    image: '/images/digital-sianage/media_display/백년시장/백년시장01.jpg',
    images: [
      '/images/digital-sianage/media_display/백년시장/백년시장01.jpg',
      '/images/digital-sianage/media_display/백년시장/백년시장02.jpg',
      '/images/digital-sianage/media_display/백년시장/백년시장03.jpg',
    ],
    specifications: {
      operatingLineup: '전통시장 맞춤형 디스플레이',
      modelName: '백년시장 미디어 디스플레이',
      productSize: '상세페이지 참조',
      resolutionBrightness: '전통시장 환경 최적화 / 적절한 밝기',
      keyFeatures: '전통시장 특화 디스플레이 / 상인과 고객 소통',
      usage: '시장 정보 안내, 상품 홍보, 이벤트 알림',
      installationMethod: '시장 내부 설치, 상인 접근성 고려',
      inquiry: '1833-9009',
    },
  },
  bulgwangcheon: {
    id: 'bulgwangcheon',
    title: '불광천 방송문화거리',
    image:
      '/images/digital-sianage/media_display/불광천 방송문화거리/불광천 방송문화거리_가로최종_깬것 [Repaired]_1.jpg',
    images: [
      '/images/digital-sianage/media_display/불광천 방송문화거리/불광천 방송문화거리_가로최종_깬것 [Repaired]_1.jpg',
      '/images/digital-sianage/media_display/불광천 방송문화거리/불광천 방송문화거리_가로최종_깬것 [Repaired]_2.jpg',
      '/images/digital-sianage/media_display/불광천 방송문화거리/불광천 방송문화거리_가로최종_깬것 [Repaired]_3.jpg',
      '/images/digital-sianage/media_display/불광천 방송문화거리/불광천 방송문화거리_가로최종_깬것 [Repaired]_4.jpg',
    ],
    specifications: {
      operatingLineup: '방송문화거리 전용 디스플레이',
      modelName: '불광천 방송문화거리 미디어 디스플레이',
      productSize: '상세페이지 참조',
      resolutionBrightness: '문화거리 환경 최적화 / 방송 콘텐츠 전용',
      keyFeatures: '방송문화거리 특화 디스플레이 / 문화 콘텐츠 송출',
      usage: '문화 이벤트, 방송 콘텐츠, 지역 문화 홍보',
      installationMethod: '문화거리 설치, 방송 연동 시스템',
      inquiry: '1833-9009',
    },
  },
  'seocho-media-pole': {
    id: 'seocho-media-pole',
    title: '서초구 미디어폴',
    image:
      '/images/digital-sianage/media_display/서초구 미디어폴/서초구 심의도서3_압축_7.jpg',
    images: [
      '/images/digital-sianage/media_display/서초구 미디어폴/서초구 심의도서3_압축_7.jpg',
      '/images/digital-sianage/media_display/서초구 미디어폴/서초구 심의도서3_압축_8.jpg',
      '/images/digital-sianage/media_display/서초구 미디어폴/서초구 심의도서3_압축_9.jpg',
      '/images/digital-sianage/media_display/서초구 미디어폴/서초구 심의도서3_압축_10.jpg',
    ],
    specifications: {
      operatingLineup: '서초구 미디어폴 시스템',
      modelName: '서초구 미디어폴 디스플레이',
      productSize: '상세페이지 참조',
      resolutionBrightness: '미디어폴 전용 디스플레이 / 도시 환경 최적화',
      keyFeatures: '서초구 특화 미디어폴 / 스마트시티 연동',
      usage: '도시 정보 안내, 공공 서비스, 스마트시티 콘텐츠',
      installationMethod: '미디어폴 설치, 스마트시티 인프라 연동',
      inquiry: '1833-9009',
    },
  },
  'seongdong-media-tunnel': {
    id: 'seongdong-media-tunnel',
    title: '성동구 미디어터널',
    image:
      '/images/digital-sianage/media_display/성동구 미디어터널/성동구 미디어터널01..jpg',
    images: [
      '/images/digital-sianage/media_display/성동구 미디어터널/성동구 미디어터널01..jpg',
      '/images/digital-sianage/media_display/성동구 미디어터널/성동구 미디어터널02.jpg',
      '/images/digital-sianage/media_display/성동구 미디어터널/성동구 미디어터널03.jpg',
      '/images/digital-sianage/media_display/성동구 미디어터널/성동구 미디어터널04.jpg',
    ],
    specifications: {
      operatingLineup: '성동구 미디어터널 시스템',
      modelName: '성동구 미디어터널 디스플레이',
      productSize: '상세페이지 참조',
      resolutionBrightness: '터널 환경 최적화 / 연속 디스플레이',
      keyFeatures: '성동구 특화 미디어터널 / 통행자 경험 향상',
      usage: '터널 내 정보 안내, 광고, 통행자 안전 정보',
      installationMethod: '터널 내 연속 설치, 안전 시스템 연동',
      inquiry: '1833-9009',
    },
  },
  'hampyeong-electronic': {
    id: 'hampyeong-electronic',
    title: '함평전자게시대',
    image: '/images/digital-sianage/media_display/함평전자게시대/함평01.jpg',
    images: [
      '/images/digital-sianage/media_display/함평전자게시대/함평01.jpg',
      '/images/digital-sianage/media_display/함평전자게시대/함평02.jpg',
      '/images/digital-sianage/media_display/함평전자게시대/함평03.jpg',
      '/images/digital-sianage/media_display/함평전자게시대/함평04.jpg',
    ],
    specifications: {
      operatingLineup: '함평 전자게시대 시스템',
      modelName: '함평전자게시대 디스플레이',
      productSize: '상세페이지 참조',
      resolutionBrightness: '전자게시대 전용 / 고휘도 디스플레이',
      keyFeatures: '함평 지역 특화 전자게시대 / 지역 정보 전용',
      usage: '지역 정보 안내, 공공 서비스, 지역 홍보',
      installationMethod: '전자게시대 설치, 지역 시스템 연동',
      inquiry: '1833-9009',
    },
  },
  // 디지털전광판
  'digital-billboard-1': {
    id: 'digital-billboard-1',
    title: 'SAMSUNG QB Series',
    image: '/images/digital-media-example.jpeg',
    specifications: {
      operatingLineup: '43인치, 50인치, 55인치, 65인치, 75인치, 85인치',
      modelName: 'QB Series (상세페이지 참조)',
      productSize: '상세페이지 참조',
      resolutionBrightness: '3,840 x 2160 (4K UHD) / 350nit',
      keyFeatures: 'USB INPUT 제어 / 매직인포 네트워크 솔루션',
      usage: '광고, 홍보, 메뉴보드, 캠페인 등의 미디어 콘텐츠 송출',
      installationMethod: '벽면설치, 매립설치, 천정설치 등',
      inquiry: '1833-9009',
    },
  },
  'digital-billboard-2': {
    id: 'digital-billboard-2',
    title: 'LG LED Display',
    image: '/images/digital-media-example.jpeg',
    specifications: {
      operatingLineup: '32인치, 43인치, 49인치, 55인치, 65인치',
      modelName: 'LG LED Series (상세페이지 참조)',
      productSize: '상세페이지 참조',
      resolutionBrightness: '1920 x 1080 (Full HD) / 400nit',
      keyFeatures: '웹OS / 스마트 디스플레이 솔루션',
      usage: '매장 디스플레이, 정보 안내, 광고 송출',
      installationMethod: '벽면설치, 스탠드설치, 천정설치 등',
      inquiry: '1833-9009',
    },
  },
  'digital-billboard-3': {
    id: 'digital-billboard-3',
    title: 'Philips Digital Signage',
    image: '/images/digital-media-example.jpeg',
    specifications: {
      operatingLineup: '40인치, 50인치, 55인치, 65인치, 75인치',
      modelName: 'Philips BDL Series (상세페이지 참조)',
      productSize: '상세페이지 참조',
      resolutionBrightness: '3840 x 2160 (4K UHD) / 450nit',
      keyFeatures: '스마트 디스플레이 / IoT 연동',
      usage: '스마트 오피스, 디지털 사이니지, 정보 디스플레이',
      installationMethod: '벽면설치, 매립설치, 이동식 스탠드 등',
      inquiry: '1833-9009',
    },
  },
  // 디지털사이니지
  'samsung-single': {
    id: 'samsung-single',
    title: '싱글 사이니지(삼성)',
    image: '/images/digital-sianage/digital_signage/1_삼성 싱글사이니지.jpg',
    type: '주문 제작형',
    modelName: '삼성 사이니지 시리즈',
    pixelPitchOptions: ['43인치', '50인치', '55인치', '75인치', '85인치'],
    description:
      '벽면 설치가 가능한 실내용 디지털 사이니지로, 대형 화면 시청이 가능하며 다양한 공간에 설치할 수 있습니다. 멀티 스크린 기능을 지원합니다.',
    specifications: {
      moduleSize: '다양한 크기 지원',
      moduleResolution: '3840 x 2160 (4K UHD)',
      pixelDensity: '고해상도 디스플레이',
      optimalViewingDistance: 'Min 1.5m ~ Max 60m',
      screenBrightness: '350nit ~ 700nit',
      pixelConfiguration: '1R1G1B',
      refreshRate: '3840Hz',
      viewingAngle: '160°/160°',
      flatness: '≤0.1mm',
      operatingTemperature: '-35°C to +50°C',
      operatingHumidity: '10% to +90%',
      ratedInput: 'AC 110~240V~(±10%)',
      maintenance: 'Front Maintenance (전면 유지보수)',
    },
    // 실제 모델 데이터
    models: {
      '43인치': [
        {
          modelName: 'LH43QHBEBGCXKR',
          resolution: '3840 x 2160',
          brightness: '700nit',
          size: '967.5 x 557.7 x 48.3',
          vesaHole: '200 x 200',
          price: '611,000원',
        },
        {
          modelName: 'LH43QMBEBGCXKR',
          resolution: '3840 x 2160',
          brightness: '500nit',
          size: '967.5 x 557.7 x 48.3',
          vesaHole: '200 x 200',
          price: '526,000원',
        },
      ],
      '50인치': [
        {
          modelName: 'LH50QHBEBGCXKR',
          resolution: '3840 x 2160',
          brightness: '700nit',
          size: '1121.4 x 643.9 x 46.3',
          vesaHole: '200 x 200',
          price: '780,000원',
        },
        {
          modelName: 'LH50QMBEBGCXKR',
          resolution: '3840 x 2160',
          brightness: '500nit',
          size: '1121.4 x 643.9 x 46.3',
          vesaHole: '200 x 200',
          price: '526,000원',
        },
      ],
      '55인치': [
        {
          modelName: 'LH55QBREBGCXKR',
          resolution: '3840 x 2160',
          brightness: '350nit',
          size: '1235.1 x 707.9 x 46.3',
          vesaHole: '200 x 200',
          price: '본품판매불가/결합형가능',
        },
      ],
      '75인치': [
        {
          modelName: 'LH75QHBEBGCXKR',
          resolution: '3840 x 2160',
          brightness: '700nit',
          size: '1681.1 x 960.1 x 49.7',
          vesaHole: '400 x 400',
          price: '1,651,000원',
        },
        {
          modelName: 'LH75QMBEBGCXKR',
          resolution: '3840 x 2160',
          brightness: '500nit',
          size: '1681.1 x 960.1 x 49.7',
          vesaHole: '400 x 400',
          price: '1,541,000원',
        },
      ],
      '85인치': [
        {
          modelName: 'LH85QBRBDGCXKR',
          resolution: '3840 x 2160',
          brightness: '350nit',
          size: '1897.8 x 1080.8 x 56.7',
          vesaHole: '600 x 400',
          price: '2,300,000원',
        },
        {
          modelName: 'LH85QMRBBGCX/KR',
          resolution: '3840 x 2160',
          brightness: '500nit',
          size: '1897.8 x 1080.8 x 56.7',
          vesaHole: '600 x 400',
          price: '2,400,000원',
        },
      ],
    },
  },
  'lg-single': {
    id: 'lg-single',
    title: '싱글 사이니지(LG)',
    image: '/images/digital-sianage/digital_signage/4_LG사이니지.jpg',
    type: '주문 제작형',
    modelName: 'LG 사이니지 시리즈',
    pixelPitchOptions: ['55인치'],
    description: 'LG의 고품질 싱글 사이니지로, 다양한 공간에 설치 가능합니다.',
    specifications: {
      moduleSize: '다양한 크기 지원',
      moduleResolution: '1920 x 1080 (Full HD)',
      pixelDensity: '고해상도 디스플레이',
      optimalViewingDistance: 'Min 1.5m ~ Max 60m',
      screenBrightness: 'Max. 350cd/m²',
      pixelConfiguration: '1R1G1B',
      refreshRate: '3840Hz',
      viewingAngle: '160°/160°',
      flatness: '≤0.1mm',
      operatingTemperature: '-35°C to +50°C',
      operatingHumidity: '10% to +90%',
      ratedInput: 'AC 110~240V~(±10%)',
      maintenance: 'Front Maintenance (전면 유지보수)',
    },
    models: {
      '55인치': [
        {
          modelName: '55SE3D-B',
          resolution: '1920 x 1080',
          brightness: 'Max. 350cd/m²',
          size: '1,238 x 714.9 x 38.6',
          vesaHole: '300 x 300',
          price: '500,000원',
        },
      ],
    },
  },
  'samsung-multivision': {
    id: 'samsung-multivision',
    title: '멀티비전',
    image: '/images/digital-sianage/digital_signage/2_삼성멀티비전.jpg',
    type: '주문 제작형',
    modelName: '삼성 멀티비전 시리즈',
    pixelPitchOptions: ['55인치'],
    description:
      '여러 개의 디스플레이를 조합하여 대형 화면을 구성하는 멀티비전 솔루션입니다.',
    specifications: {
      moduleSize: '다양한 크기 지원',
      moduleResolution: '1920 x 1080 (Full HD)',
      pixelDensity: '고해상도 디스플레이',
      optimalViewingDistance: 'Min 1.5m ~ Max 60m',
      screenBrightness: '500nit ~ 700nit',
      pixelConfiguration: '1R1G1B',
      refreshRate: '3840Hz',
      viewingAngle: '160°/160°',
      flatness: '≤0.1mm',
      operatingTemperature: '-35°C to +50°C',
      operatingHumidity: '10% to +90%',
      ratedInput: 'AC 110~240V~(±10%)',
      maintenance: 'Front Maintenance (전면 유지보수)',
    },
    models: {
      '55인치': [
        {
          modelName: 'LH55VHRRBGBXKR',
          resolution: '1920 x 1080',
          brightness: '700nit',
          size: '1211.0 x 681.7 x 69.9',
          vesaHole: '600 x 400',
          price: '3,100,000원',
        },
        {
          modelName: 'LH55VMCRBGBXKR',
          resolution: '1920 x 1080',
          brightness: '500nit',
          size: '1211.0 x 681.7 x 69.9',
          vesaHole: '600 x 400',
          price: '1,850,000원',
        },
        {
          modelName: 'LH55VMBRBGBXKR',
          resolution: '1920 x 1080',
          brightness: '500nit',
          size: '1211.0 x 681.7 x 69.9',
          vesaHole: '600 x 400',
          price: '2,700,000원',
        },
      ],
    },
  },
  'samsung-chalkboard': {
    id: 'samsung-chalkboard',
    title: '전자칠판',
    image: '/images/digital-sianage/digital_signage/3_삼성전지칠판.jpg',
    type: '주문 제작형',
    modelName: '삼성 전자칠판 시리즈',
    pixelPitchOptions: ['55인치', '85인치'],
    description: '교육 및 회의 환경에 최적화된 터치 인터랙티브 전자칠판입니다.',
    specifications: {
      moduleSize: '다양한 크기 지원',
      moduleResolution: '3840 x 2160 (4K UHD)',
      pixelDensity: '고해상도 디스플레이',
      optimalViewingDistance: 'Min 1.5m ~ Max 60m',
      screenBrightness: '350nit',
      pixelConfiguration: '1R1G1B',
      refreshRate: '3840Hz',
      viewingAngle: '160°/160°',
      flatness: '≤0.1mm',
      operatingTemperature: '-35°C to +50°C',
      operatingHumidity: '10% to +90%',
      ratedInput: 'AC 110~240V~(±10%)',
      maintenance: 'Front Maintenance (전면 유지보수)',
    },
    models: {
      '55인치': [
        {
          modelName: 'LH55WMBWBGCXKR',
          resolution: '3840 x 2160',
          brightness: '350nit',
          size: '1297.4 x 768.2 x 59.9',
          vesaHole: '400 x 400',
          price: '1,274,000원',
        },
      ],
      '85인치': [
        {
          modelName: 'LH85WMBWLGCXKR',
          resolution: '3840 x 2160',
          brightness: '350nit',
          size: '1945.8 x 1151.1 x 89',
          vesaHole: '600 x 400',
          price: '0원',
        },
      ],
    },
  },
  'samsung-kiosk': {
    id: 'samsung-kiosk',
    title: '결제키오스크(삼성)',
    image:
      '/images/digital-sianage/digital_signage/6_삼성전자결제-키오스크.jpg',
    type: '주문 제작형',
    modelName: '삼성 키오스크 시리즈',
    pixelPitchOptions: ['24인치'],
    description:
      '결제 시스템이 통합된 터치스크린 키오스크로, 매장 및 편의점에 최적화되어 있습니다.',
    specifications: {
      moduleSize: '다양한 크기 지원',
      moduleResolution: '1920 x 1080 (Full HD)',
      pixelDensity: '고해상도 디스플레이',
      optimalViewingDistance: 'Min 0.5m ~ Max 3m',
      screenBrightness: '250nit',
      pixelConfiguration: '1R1G1B',
      refreshRate: '3840Hz',
      viewingAngle: '160°/160°',
      flatness: '≤0.1mm',
      operatingTemperature: '-35°C to +50°C',
      operatingHumidity: '10% to +90%',
      ratedInput: 'AC 110~240V~(±10%)',
      maintenance: 'Front Maintenance (전면 유지보수)',
    },
    models: {
      '24인치': [
        {
          modelName: 'LH24KMATBGCXKR',
          resolution: '1920 x 1080',
          brightness: '250nit',
          size: '334 x 733 x 236',
          vesaHole: '-',
          price: '1,000,000원',
        },
      ],
    },
  },
  'lg-signage': {
    id: 'lg-signage',
    title: 'LG 사이니지',
    image: '/images/digital-sianage/digital_signage/4_LG사이니지.jpg',
    specifications: {
      operatingLineup: '55인치, 65인치, 75인치, 86인치',
      modelName: 'LG Signage Series (상세페이지 참조)',
      productSize: '상세페이지 참조',
      resolutionBrightness: '3840 x 2160 (4K UHD) / 350-500nit',
      keyFeatures: '4K 해상도 / 상업용 디스플레이',
      usage: '상업시설, 호텔, 레스토랑 디스플레이',
      installationMethod: '벽면설치, 스탠드, 매립설치 등',
      inquiry: '1833-9009',
    },
  },
  'stand-signage': {
    id: 'stand-signage',
    title: '스탠다드 사이니지',
    image: '/images/digital-sianage/digital_signage/5_중국산 스탠드.jpg',
    type: '주문 제작형',
    modelName: 'P Series (피벗형 회전형)',
    pixelPitchOptions: ['43인치', '49인치', '55인치'],
    description:
      '피벗형 회전형 스탠드 사이니지로, 다양한 환경에 설치 가능합니다.',
    specifications: {
      moduleSize: '다양한 크기 지원',
      moduleResolution: '3840 x 2160 (4K UHD)',
      pixelDensity: '고해상도 디스플레이',
      optimalViewingDistance: 'Min 1m ~ Max 30m',
      screenBrightness: '500nit',
      pixelConfiguration: '1R1G1B',
      refreshRate: '3840Hz',
      viewingAngle: '160°/160°',
      flatness: '≤0.1mm',
      operatingTemperature: '-35°C to +50°C',
      operatingHumidity: '10% to +90%',
      ratedInput: 'AC 110~240V~(±10%)',
      maintenance: 'Front Maintenance (전면 유지보수)',
    },
    models: {
      '43인치': [
        {
          modelName: 'DS430PU',
          resolution: '3840 x 2160',
          brightness: '500nit',
          size: '1000.6 x 1575.9 (가로 거치) / 589.6 x 1781.4 (세로 거치)',
          vesaHole: 'U (USB 타입)',
          price: '1,307,000원',
          stock: '배송,설치비 별도',
        },
        {
          modelName: 'DS430PN',
          resolution: '3840 x 2160',
          brightness: '500nit',
          size: '1000.6 x 1575.9 (가로 거치) / 589.6 x 1781.4 (세로 거치)',
          vesaHole: 'N (네트워크 타입)',
          price: '1,428,000원',
          stock: '배송,설치비 별도',
        },
        {
          modelName: 'DS430PP',
          resolution: '3840 x 2160',
          brightness: '500nit',
          size: '1000.6 x 1575.9 (가로 거치) / 589.6 x 1781.4 (세로 거치)',
          vesaHole: 'P (PC 셀러론 타입)',
          price: '1,573,000원',
          stock: '배송,설치비 별도',
        },
        {
          modelName: 'DS430PPT',
          resolution: '3840 x 2160',
          brightness: '500nit',
          size: '1000.6 x 1575.9 (가로 거치) / 589.6 x 1781.4 (세로 거치)',
          vesaHole: 'PT (PC 셀러론+터치 타입)',
          price: '1,722,000원',
          stock: '배송,설치비 별도',
        },
      ],
      '49인치': [
        {
          modelName: 'DS490PU',
          resolution: '3840 x 2160',
          brightness: '500nit',
          size: '1124 x 1608.1 (가로 거치) / 654 x 1843.1 (세로 거치)',
          vesaHole: 'U (USB 타입)',
          price: '1,377,000원',
          stock: '배송,설치비 별도',
        },
        {
          modelName: 'DS490PN',
          resolution: '3840 x 2160',
          brightness: '500nit',
          size: '1124 x 1608.1 (가로 거치) / 654 x 1843.1 (세로 거치)',
          vesaHole: 'N (네트워크 타입)',
          price: '1,505,000원',
          stock: '배송,설치비 별도',
        },
        {
          modelName: 'DS490PP',
          resolution: '3840 x 2160',
          brightness: '500nit',
          size: '1124 x 1608.1 (가로 거치) / 654 x 1843.1 (세로 거치)',
          vesaHole: 'P (PC 셀러론 타입)',
          price: '1,644,000원',
          stock: '배송,설치비 별도',
        },
        {
          modelName: 'DS490PPT',
          resolution: '3840 x 2160',
          brightness: '500nit',
          size: '1124 x 1608.1 (가로 거치) / 654 x 1843.1 (세로 거치)',
          vesaHole: 'PT (PC 셀러론+터치 타입)',
          price: '1,826,000원',
          stock: '배송,설치비 별도',
        },
      ],
      '55인치': [
        {
          modelName: 'DS550PU',
          resolution: '3840 x 2160',
          brightness: '500nit',
          size: '1258 x 1650.1 (가로 거치) / 738 x 1910.1 (세로 거치)',
          vesaHole: 'U (USB 타입)',
          price: '1,431,000원',
          stock: '배송,설치비 별도',
        },
        {
          modelName: 'DS550PN',
          resolution: '3840 x 2160',
          brightness: '500nit',
          size: '1258 x 1650.1 (가로 거치) / 738 x 1910.1 (세로 거치)',
          vesaHole: 'N (네트워크 타입)',
          price: '1,560,000원',
          stock: '배송,설치비 별도',
        },
        {
          modelName: 'DS550PP',
          resolution: '3840 x 2160',
          brightness: '500nit',
          size: '1258 x 1650.1 (가로 거치) / 738 x 1910.1 (세로 거치)',
          vesaHole: 'P (PC 셀러론 타입)',
          price: '1,699,000원',
          stock: '배송,설치비 별도',
        },
        {
          modelName: 'DS550PPT',
          resolution: '3840 x 2160',
          brightness: '500nit',
          size: '1258 x 1650.1 (가로 거치) / 738 x 1910.1 (세로 거치)',
          vesaHole: 'PT (PC 셀러론+터치 타입)',
          price: '1,924,000원',
          stock: '배송,설치비 별도',
        },
      ],
    },
  },
  'multivision-videowall': {
    id: 'multivision-videowall',
    title: '멀티비전(비디오월)',
    image: '/images/digital-sianage/digital_signage/7_멀티비전 이미지1.jpg',
    type: '주문 제작형',
    modelName: 'VW Series',
    pixelPitchOptions: ['55인치(2.6mm)', '55인치(0.88mm)'],
    description:
      '대형 비디오월 구성이 가능한 멀티비전 솔루션으로, 이벤트 및 전시 공간에 적합합니다.',
    specifications: {
      moduleSize: '다양한 크기 지원',
      moduleResolution: '1920 x 1080 (Full HD)',
      pixelDensity: '고해상도 디스플레이',
      optimalViewingDistance: 'Min 1.5m ~ Max 60m',
      screenBrightness: '500nit ~ 700nit',
      pixelConfiguration: '1R1G1B',
      refreshRate: '3840Hz',
      viewingAngle: '160°/160°',
      flatness: '≤0.1mm',
      operatingTemperature: '-35°C to +50°C',
      operatingHumidity: '10% to +90%',
      ratedInput: 'AC 110~240V~(±10%)',
      maintenance: 'Front Maintenance (전면 유지보수)',
    },
    models: {
      '55인치(2.6mm)': [
        {
          modelName: 'VW550E-5LW',
          resolution: '1920 x 1080',
          brightness: '500nit',
          size: '1212.2 x 683 x 92.5',
          vesaHole: '2.6mm / 500nit',
          price: '1,434,000원',
          stock: '무게: 19.6kg',
        },
        {
          modelName: 'VW550E-7LW',
          resolution: '1920 x 1080',
          brightness: '700nit',
          size: '-',
          vesaHole: '2.6mm / 700nit',
          price: '1,640,000원',
          stock: '무게: 19.7kg',
        },
      ],
      '55인치(0.88mm)': [
        {
          modelName: 'VW550R-5LW',
          resolution: '1920 x 1080',
          brightness: '500nit',
          size: '1210.51 x 681.22 x 92.4',
          vesaHole: '0.88mm / 500nit',
          price: '1,840,000원',
          stock: '무게: 18.5kg',
        },
        {
          modelName: 'VW550R-7LW',
          resolution: '1920 x 1080',
          brightness: '700nit',
          size: '-',
          vesaHole: '0.88mm / 700nit',
          price: '2,021,000원',
          stock: '무게: 18.1kg',
        },
        {
          modelName: 'VW550R-5LW_경량2',
          resolution: '1920 x 1080',
          brightness: '500nit',
          size: '매그놀리아',
          vesaHole: '0.88mm / 500nit',
          price: '1,700,000원',
          stock: '무게 별도 문의',
        },
        {
          modelName: 'VW550R-7LW_경량2',
          resolution: '1920 x 1080',
          brightness: '700nit',
          size: '매그놀리아',
          vesaHole: '0.88mm / 700nit',
          price: '1,870,000원',
          stock: '무게 별도 문의',
        },
      ],
    },
  },
  'aida-digital-frame': {
    id: 'aida-digital-frame',
    title: '디지털액자',
    image: '/images/digital-sianage/digital_signage/8_AIDA 디지털액자.jpg',
    type: '주문 제작형',
    modelName: 'AIDA 디지털액자 시리즈',
    pixelPitchOptions: ['10인치'],
    description: '예술작품 및 사진 전시에 최적화된 디지털 액자 솔루션입니다.',
    specifications: {
      moduleSize: '다양한 크기 지원',
      moduleResolution: '800 x 1280',
      pixelDensity: '고품질 디스플레이',
      optimalViewingDistance: 'Min 0.5m ~ Max 10m',
      screenBrightness: '250cd/m²',
      pixelConfiguration: '1R1G1B',
      refreshRate: '3840Hz',
      viewingAngle: '160°/160°',
      flatness: '≤0.1mm',
      operatingTemperature: '-35°C to +50°C',
      operatingHumidity: '10% to +90%',
      ratedInput: 'AC 110~240V~(±10%)',
      maintenance: 'Front Maintenance (전면 유지보수)',
    },
    models: {
      '10인치': [
        {
          modelName: 'AIDA1004IPS',
          resolution: '800 x 1280',
          brightness: '250cd/m²',
          size: '169 x 365 x 59',
          vesaHole: 'USB',
          price: '110,000원',
          stock: '디지털액자(콘텐츠)',
        },
      ],
    },
  },
  'the-gallery': {
    id: 'the-gallery',
    title: '더갤러리(삼성)',
    image: '/images/digital-sianage/digital_signage/10_더갤러리.png',
    type: '주문 제작형',
    modelName: '더갤러리 시리즈',
    pixelPitchOptions: ['다양한 크기'],
    description:
      '미술관 및 갤러리 전용으로 설계된 고품질 디지털 사이니지입니다.',
    specifications: {
      moduleSize: '다양한 크기 지원',
      moduleResolution: '고해상도',
      pixelDensity: '고품질 디스플레이',
      optimalViewingDistance: 'Min 1m ~ Max 30m',
      screenBrightness: '300nit ~ 500nit',
      pixelConfiguration: '1R1G1B',
      refreshRate: '3840Hz',
      viewingAngle: '160°/160°',
      flatness: '≤0.1mm',
      operatingTemperature: '-35°C to +50°C',
      operatingHumidity: '10% to +90%',
      ratedInput: 'AC 110~240V~(±10%)',
      maintenance: 'Front Maintenance (전면 유지보수)',
    },
    models: {
      '다양한 크기': [
        {
          modelName: '더갤러리 시리즈',
          resolution: '고해상도',
          brightness: '300nit ~ 500nit',
          size: '다양한 크기',
          vesaHole: '표준',
          price: '문의',
          stock: '주문 제작',
        },
      ],
    },
  },
  'q-series-stand': {
    id: 'q-series-stand',
    title: '스탠드 사이니지(Q시리즈)',
    image:
      '/images/digital-sianage/digital_signage/11_Q시리즈 스탠드사이니지.jpg',
    type: '주문 제작형',
    modelName: 'Q시리즈 스탠드 사이니지',
    pixelPitchOptions: ['다양한 크기'],
    description:
      'Q시리즈의 고품질 스탠드 사이니지로, 다양한 환경에 설치 가능합니다.',
    specifications: {
      moduleSize: '다양한 크기 지원',
      moduleResolution: '고해상도',
      pixelDensity: '고품질 디스플레이',
      optimalViewingDistance: 'Min 1m ~ Max 30m',
      screenBrightness: '300nit ~ 500nit',
      pixelConfiguration: '1R1G1B',
      refreshRate: '3840Hz',
      viewingAngle: '160°/160°',
      flatness: '≤0.1mm',
      operatingTemperature: '-35°C to +50°C',
      operatingHumidity: '10% to +90%',
      ratedInput: 'AC 110~240V~(±10%)',
      maintenance: 'Front Maintenance (전면 유지보수)',
    },
    models: {
      '다양한 크기': [
        {
          modelName: 'Q시리즈 스탠드 사이니지',
          resolution: '고해상도',
          brightness: '300nit ~ 500nit',
          size: '다양한 크기',
          vesaHole: '표준',
          price: '문의',
          stock: '주문 제작',
        },
      ],
    },
  },
  'q-series-touch': {
    id: 'q-series-touch',
    title: '터치모니터(Q시리즈)',
    image: '/images/digital-sianage/digital_signage/12_Q시리즈 터치모니터.jpg',
    type: '주문 제작형',
    modelName: 'Q시리즈 터치모니터',
    pixelPitchOptions: ['다양한 크기'],
    description:
      'Q시리즈의 터치 인터랙티브 모니터로, 사용자 경험을 향상시킵니다.',
    specifications: {
      moduleSize: '다양한 크기 지원',
      moduleResolution: '고해상도',
      pixelDensity: '고품질 디스플레이',
      optimalViewingDistance: 'Min 0.5m ~ Max 5m',
      screenBrightness: '300nit ~ 500nit',
      pixelConfiguration: '1R1G1B',
      refreshRate: '3840Hz',
      viewingAngle: '160°/160°',
      flatness: '≤0.1mm',
      operatingTemperature: '-35°C to +50°C',
      operatingHumidity: '10% to +90%',
      ratedInput: 'AC 110~240V~(±10%)',
      maintenance: 'Front Maintenance (전면 유지보수)',
    },
    models: {
      '다양한 크기': [
        {
          modelName: 'Q시리즈 터치모니터',
          resolution: '고해상도',
          brightness: '300nit ~ 500nit',
          size: '다양한 크기',
          vesaHole: '표준',
          price: '문의',
          stock: '주문 제작',
        },
      ],
    },
  },
  'outdoor-wall': {
    id: 'outdoor-wall',
    title: '옥외형 벽부타입',
    image: '/images/digital-sianage/digital_signage/14_옥외형 벽부형.jpg',
    type: '주문 제작형',
    modelName: '아웃도어 (옥외형)',
    pixelPitchOptions: ['벽부형', '스탠드형'],
    description: '야외 환경에 최적화된 벽면 설치형 디지털 사이니지입니다.',
    specifications: {
      moduleSize: '다양한 크기 지원',
      moduleResolution: '1920 x 1080 ~ 3840 x 2160',
      pixelDensity: '고품질 디스플레이',
      optimalViewingDistance: 'Min 2m ~ Max 100m',
      screenBrightness: '2,500cd/m² ~ 3,000cd/m²',
      pixelConfiguration: '1R1G1B',
      refreshRate: '3840Hz',
      viewingAngle: '160°/160°',
      flatness: '≤0.1mm',
      operatingTemperature: '-40°C to +60°C',
      operatingHumidity: '5% to +95%',
      ratedInput: 'AC 110~240V~(±10%)',
      maintenance: 'Front Maintenance (전면 유지보수)',
    },
    models: {
      벽부형: [
        {
          modelName: 'ODW550P',
          brand: '벽부형',
          inch: '55인치',
          size: '1410 x 1023.8 x 270',
          vesaHole: 'P (PC i3 타입)',
          resolution: '1920 x 1080',
          brightness: '2,500cd/m²',
          price: '5,560,000원',
          stock: '벽부형 55인치',
        },
        {
          modelName: 'ODW550PT',
          brand: '벽부형',
          inch: '55인치',
          size: '1410 x 1023.8 x 270',
          vesaHole: 'PT (PC i3+PCAP 터치타입)',
          resolution: '1920 x 1080',
          brightness: '2,500cd/m²',
          price: '6,960,000원',
          stock: '벽부형 55인치 Touch',
        },
        {
          modelName: 'ODW750P',
          brand: '벽부형',
          inch: '75인치',
          size: '1850 x 1270 x 270',
          vesaHole: 'P (PC i3 타입)',
          resolution: '3840 x 2160',
          brightness: '3,000cd/m²',
          price: '7,730,000원',
          stock: '벽부형 75인치',
        },
      ],
      스탠드형: [
        {
          modelName: 'ODS550P',
          brand: '스탠드형',
          inch: '55인치',
          size: '860 x 1970 x 500',
          vesaHole: 'P (PC i3 타입)',
          resolution: '1920 x 1080',
          brightness: '2,500cd/m²',
          price: '5,360,000원',
          stock: '자립형 55인치',
        },
        {
          modelName: 'ODS550PT',
          brand: '스탠드형',
          inch: '55인치',
          size: '860 x 1970 x 500',
          vesaHole: 'PT (PC i3+PCAP 터치타입)',
          resolution: '1920 x 1080',
          brightness: '2,500cd/m²',
          price: '6,200,000원',
          stock: '자립형 55인치 Touch',
        },
        {
          modelName: 'ODS750P',
          brand: '스탠드형',
          inch: '75인치',
          size: '1140 x 2200 x 600',
          vesaHole: 'P (PC i3 타입)',
          resolution: '3840 x 2160',
          brightness: '3,000cd/m²',
          price: '8,330,000원',
          stock: '자립형 75인치',
        },
        {
          modelName: 'ODS750PT',
          brand: '스탠드형',
          inch: '75인치',
          size: '1140 x 2200 x 600',
          vesaHole: 'PT (PC i3+PCAP 터치타입)',
          resolution: '3840 x 2160',
          brightness: '3,000cd/m²',
          price: '9,530,000원',
          stock: '자립형 75인치 Touch',
        },
      ],
    },
  },
  'outdoor-stand': {
    id: 'outdoor-stand',
    title: '옥외형 스탠드타입',
    image: '/images/digital-sianage/digital_signage/15_옥외형 스탠드형1.jpg',
    type: '주문 제작형',
    modelName: '아웃도어 (옥외형)',
    pixelPitchOptions: ['벽부형', '스탠드형'],
    description: '야외 환경에 최적화된 스탠드 설치형 디지털 사이니지입니다.',
    specifications: {
      moduleSize: '다양한 크기 지원',
      moduleResolution: '1920 x 1080 ~ 3840 x 2160',
      pixelDensity: '고품질 디스플레이',
      optimalViewingDistance: 'Min 2m ~ Max 100m',
      screenBrightness: '2,500cd/m² ~ 3,000cd/m²',
      pixelConfiguration: '1R1G1B',
      refreshRate: '3840Hz',
      viewingAngle: '160°/160°',
      flatness: '≤0.1mm',
      operatingTemperature: '-40°C to +60°C',
      operatingHumidity: '5% to +95%',
      ratedInput: 'AC 110~240V~(±10%)',
      maintenance: 'Front Maintenance (전면 유지보수)',
    },
    models: {
      벽부형: [
        {
          modelName: 'ODW550P',
          brand: '벽부형',
          inch: '55인치',
          size: '1410 x 1023.8 x 270',
          vesaHole: 'P (PC i3 타입)',
          resolution: '1920 x 1080',
          brightness: '2,500cd/m²',
          price: '5,560,000원',
          stock: '벽부형 55인치',
        },
        {
          modelName: 'ODW550PT',
          brand: '벽부형',
          inch: '55인치',
          size: '1410 x 1023.8 x 270',
          vesaHole: 'PT (PC i3+PCAP 터치타입)',
          resolution: '1920 x 1080',
          brightness: '2,500cd/m²',
          price: '6,960,000원',
          stock: '벽부형 55인치 Touch',
        },
        {
          modelName: 'ODW750P',
          brand: '벽부형',
          inch: '75인치',
          size: '1850 x 1270 x 270',
          vesaHole: 'P (PC i3 타입)',
          resolution: '3840 x 2160',
          brightness: '3,000cd/m²',
          price: '7,730,000원',
          stock: '벽부형 75인치',
        },
      ],
      스탠드형: [
        {
          modelName: 'ODS550P',
          brand: '스탠드형',
          inch: '55인치',
          size: '860 x 1970 x 500',
          vesaHole: 'P (PC i3 타입)',
          resolution: '1920 x 1080',
          brightness: '2,500cd/m²',
          price: '5,360,000원',
          stock: '자립형 55인치',
        },
        {
          modelName: 'ODS550PT',
          brand: '스탠드형',
          inch: '55인치',
          size: '860 x 1970 x 500',
          vesaHole: 'PT (PC i3+PCAP 터치타입)',
          resolution: '1920 x 1080',
          brightness: '2,500cd/m²',
          price: '6,200,000원',
          stock: '자립형 55인치 Touch',
        },
        {
          modelName: 'ODS750P',
          brand: '스탠드형',
          inch: '75인치',
          size: '1140 x 2200 x 600',
          vesaHole: 'P (PC i3 타입)',
          resolution: '3840 x 2160',
          brightness: '3,000cd/m²',
          price: '8,330,000원',
          stock: '자립형 75인치',
        },
        {
          modelName: 'ODS750PT',
          brand: '스탠드형',
          inch: '75인치',
          size: '1140 x 2200 x 600',
          vesaHole: 'PT (PC i3+PCAP 터치타입)',
          resolution: '3840 x 2160',
          brightness: '3,000cd/m²',
          price: '9,530,000원',
          stock: '자립형 75인치 Touch',
        },
      ],
    },
  },
  'led-display': {
    id: 'led-display',
    title: 'LED 디스플레이 시리즈',
    image: '/images/digital-sianage/digital_signage/16_LED디스플레이.jpg',
    type: '주문 제작형',
    modelName: 'LED 디스플레이 시리즈',
    pixelPitchOptions: [
      'LED 캐비닛 (P1.25)',
      'LED 캐비닛 (P1.56)',
      'LED 캐비닛 (P1.87)',
      'LED 캐비닛 (P2.5)',
    ],
    description:
      '고휘도 LED 디스플레이 시리즈로, 다양한 환경에서 사용 가능합니다.',
    specifications: {
      moduleSize: '다양한 크기 지원',
      moduleResolution: '192 x 192 ~ 480 x 270',
      pixelDensity: '고품질 디스플레이',
      optimalViewingDistance: 'Min 1.5m ~ Max 60m',
      screenBrightness: '600cd/m²',
      pixelConfiguration: '1R1G1B',
      refreshRate: '3840Hz',
      viewingAngle: '160°/160°',
      flatness: '≤0.1mm',
      operatingTemperature: '-35°C to +50°C',
      operatingHumidity: '10% to +90%',
      ratedInput: 'AC 110~240V~(±10%)',
      maintenance: 'Front Maintenance (전면 유지보수)',
    },
    models: {
      'LED 캐비닛 (P1.25)': [
        {
          modelName: 'SM-125H',
          brand: 'LED 캐비닛',
          inch: '27인치',
          size: '600 x 337.5 x 31 (16:9)',
          vesaHole: '-',
          resolution: '480 x 270',
          brightness: '600cd/m²',
          price: '1,037,000원',
          stock:
            '실내형 (Indoor), Pitch 1.25 mm, 인테리어, 설치비, 프레임, 배송비 별도',
        },
      ],
      'LED 캐비닛 (P1.56)': [
        {
          modelName: 'SM-156H',
          brand: 'LED 캐비닛',
          inch: '27.1인치',
          size: '600 x 337.5 x 31 (16:9)',
          vesaHole: '-',
          resolution: '384 x 216',
          brightness: '600cd/m²',
          price: '653,000원',
          stock:
            '실내형 (Indoor), Pitch 1.56 mm, 인테리어, 설치비, 프레임, 배송비 별도',
        },
      ],
      'LED 캐비닛 (P1.87)': [
        {
          modelName: 'SM-187H',
          brand: 'LED 캐비닛',
          inch: '27.1인치',
          size: '600 x 337.5 x 31 (16:9)',
          vesaHole: '-',
          resolution: '320 x 180',
          brightness: '600cd/m²',
          price: '564,000원',
          stock:
            '실내형 (Indoor), Pitch 1.87 mm, 인테리어, 설치비, 프레임, 배송비 별도',
        },
      ],
      'LED 캐비닛 (P2.5)': [
        {
          modelName: 'SM-250H',
          brand: 'LED 캐비닛',
          inch: '26.7인치',
          size: '480 x 480 x 50.8 (1:1)',
          vesaHole: '-',
          resolution: '192 x 192',
          brightness: '600cd/m²',
          price: '400,000원',
          stock:
            '실내형 (Indoor), Pitch 2.5 mm, 인테리어, 설치비, 프레임, 배송비 별도',
        },
      ],
    },
  },
  'led-controller': {
    id: 'led-controller',
    title: 'LED 디스플레이 컨트롤러',
    image: '/images/digital-sianage/digital_signage/17_1-컨트롤러-PC형.jpg',
    type: '주문 제작형',
    modelName: 'LED 컨트롤러 시리즈',
    pixelPitchOptions: ['컨트롤러 PC형', '컨트롤러 HD용', '컨트롤러 FHD용'],
    description: 'LED 디스플레이 제어를 위한 전문 컨트롤러 시스템입니다.',
    specifications: {
      moduleSize: '다양한 크기 지원',
      moduleResolution: '다양한 해상도 지원',
      pixelDensity: '고품질 제어',
      optimalViewingDistance: '제어 거리 무관',
      screenBrightness: '제어 가능',
      pixelConfiguration: '다양한 구성 지원',
      refreshRate: '3840Hz',
      viewingAngle: '제어 무관',
      flatness: '≤0.1mm',
      operatingTemperature: '-35°C to +50°C',
      operatingHumidity: '10% to +90%',
      ratedInput: 'AC 110~240V~(±10%)',
      maintenance: 'Front Maintenance (전면 유지보수)',
    },
    models: {
      '컨트롤러 PC형': [
        {
          modelName: 'PC형',
          brand: '컨트롤러',
          inch: '-',
          size: '335 x 190 x 14',
          vesaHole: '-',
          resolution: '-',
          brightness: '-',
          price: '180,000원',
          stock: 'PC형 컨트롤러',
        },
      ],
      '컨트롤러 HD용': [
        {
          modelName: 'HD용',
          brand: '컨트롤러',
          inch: '-',
          size: '204 x 160 x 48',
          vesaHole: '-',
          resolution: '-',
          brightness: '-',
          price: '200,000원',
          stock: 'HD용 컨트롤러',
        },
      ],
      '컨트롤러 FHD용': [
        {
          modelName: 'MCTRL600',
          brand: '컨트롤러',
          inch: '-',
          size: '482 x 268.5 x 44.4',
          vesaHole: '-',
          resolution: '-',
          brightness: '-',
          price: '650,000원',
          stock: 'FHD용 컨트롤러',
        },
        {
          modelName: 'MCTRL 660 PRO',
          brand: '컨트롤러',
          inch: '-',
          size: '-',
          vesaHole: '-',
          resolution: '-',
          brightness: '-',
          price: '1,190,000원',
          stock: 'FHD용 컨트롤러 PRO',
        },
      ],
    },
  },
  'led-installation': {
    id: 'led-installation',
    title: 'LED 디스플레이 설치비',
    image:
      '/images/digital-sianage/digital_signage/18_LED 디스플레이 설치비.png',
    type: '서비스',
    modelName: 'LED 설치 서비스',
    pixelPitchOptions: ['설치/브라켓 포함'],
    description: 'LED 디스플레이 설치 및 유지보수 서비스를 제공합니다.',
    specifications: {
      moduleSize: '다양한 크기 지원',
      moduleResolution: '다양한 해상도 지원',
      pixelDensity: '고품질 설치',
      optimalViewingDistance: '설치 환경에 따라',
      screenBrightness: '설정 가능',
      pixelConfiguration: '다양한 구성 지원',
      refreshRate: '3840Hz',
      viewingAngle: '설치 각도 조정',
      flatness: '≤0.1mm',
      operatingTemperature: '-35°C to +50°C',
      operatingHumidity: '10% to +90%',
      ratedInput: 'AC 110~240V~(±10%)',
      maintenance: 'Front Maintenance (전면 유지보수)',
    },
    models: {
      '설치/브라켓 포함': [
        {
          modelName: '설치 서비스',
          brand: 'LED 설치',
          inch: '-',
          size: '-',
          vesaHole: '-',
          resolution: '-',
          brightness: '-',
          price: '75,000원',
          stock: '설치후 1~2회 방문, 캐비넷당',
        },
      ],
    },
  },
  bracket: {
    id: 'bracket',
    title: '브라켓',
    image: '/images/digital-sianage/digital_signage/13_브라켓 NSV-01.jpg',
    type: '주문 제작형',
    modelName: '브라켓 시리즈',
    pixelPitchOptions: ['벽부 팝업 브라켓', '대형 대형 브라켓'],
    description:
      '다양한 설치 환경에 맞는 브라켓 및 마운트 시스템을 제공합니다.',
    specifications: {
      moduleSize: '다양한 크기 지원',
      moduleResolution: '설치 무관',
      pixelDensity: '설치 무관',
      optimalViewingDistance: '설치 환경에 따라',
      screenBrightness: '설치 무관',
      pixelConfiguration: '설치 무관',
      refreshRate: '설치 무관',
      viewingAngle: '설치 각도 조정',
      flatness: '≤0.1mm',
      operatingTemperature: '-35°C to +50°C',
      operatingHumidity: '10% to +90%',
      ratedInput: '설치 무관',
      maintenance: '설치 후 유지보수',
    },
    models: {
      '벽부 팝업 브라켓': [
        {
          modelName: 'NSV-01',
          brand: '벽부 팝업 브라켓',
          inch: '-',
          size: '-',
          vesaHole: '최소 200 x 200 / 최대 600 x 400',
          resolution: '-',
          brightness: '-',
          price: '130,000원',
          stock: '최대 하중 45kg',
        },
      ],
      '대형 대형 브라켓': [
        {
          modelName: 'PV-70',
          brand: '대형 대형 브라켓',
          inch: '98인치 설치가능',
          size: '-',
          vesaHole: '최소 200 x 200 / 최대 1200 x 600',
          resolution: '-',
          brightness: '-',
          price: '110,000원',
          stock: '최대 하중 200kg',
        },
      ],
    },
  },
  'electronic-whiteboard': {
    id: 'electronic-whiteboard',
    title: '전자칠판',
    image: '/images/digital-sianage/digital_signage/4_전자칠판.jpg',
    type: '주문 제작형',
    modelName: '삼성 전자칠판 시리즈',
    pixelPitchOptions: ['55인치', '85인치', '브라켓', '트레이'],
    description:
      '교육 및 회의 환경에 최적화된 인터랙티브 전자칠판 솔루션입니다.',
    specifications: {
      moduleSize: '다양한 크기 지원',
      moduleResolution: '3840 x 2160 (4K UHD)',
      pixelDensity: '고해상도 디스플레이',
      optimalViewingDistance: 'Min 1m ~ Max 10m',
      screenBrightness: '350nit',
      pixelConfiguration: '1R1G1B',
      refreshRate: '3840Hz',
      viewingAngle: '160°/160°',
      flatness: '≤0.1mm',
      operatingTemperature: '-35°C to +50°C',
      operatingHumidity: '10% to +90%',
      ratedInput: 'AC 110~240V~(±10%)',
      maintenance: 'Front Maintenance (전면 유지보수)',
    },
    models: {
      '55인치': [
        {
          modelName: 'LH55WMBWBGCXKR',
          resolution: '3840 x 2160',
          brightness: '350nit',
          size: '1297.4 x 768.2 x 59.9 mm',
          vesaHole: '400 x 400',
          price: '1,274,000원',
        },
      ],
      '85인치': [
        {
          modelName: 'LH85WMBWLGCXKR',
          resolution: '3840 x 2160',
          brightness: '350nit',
          size: '1945.8 x 1151.1 x 89',
          vesaHole: '600 x 400',
          price: '0원',
        },
      ],
      브라켓: [
        {
          modelName: 'HA-AF-STAND-BK (Flip 55형/65형)',
          resolution: '-',
          brightness: '-',
          size: '1000 x 1714 x 500',
          vesaHole: 'Flip 55"/65" 스탠드 브라켓',
          price: '720,000원',
        },
        {
          modelName: 'HA-AFN-S7585-WH (Flip 75형/85형)',
          resolution: '-',
          brightness: '-',
          size: '1000 x 1714 x 500',
          vesaHole: '600 x 400',
          price: '930,000원',
        },
        {
          modelName: 'WMN-WM65RXKR',
          resolution: '-',
          brightness: '-',
          size: '-',
          vesaHole: '400 x 400',
          price: '171,000원',
        },
      ],
      트레이: [
        {
          modelName: 'CY-TF65BRCXKR',
          resolution: '-',
          brightness: '-',
          size: '269.8 x 111.3 x 56.9',
          vesaHole: '-',
          price: '150,000원',
        },
      ],
    },
  },
  kiosk: {
    id: 'kiosk',
    title: '결제키오스크(삼성)',
    image: '/images/digital-sianage/digital_signage/6_키오스크.jpg',
    type: '주문 제작형',
    modelName: '삼성전자 결제 키오스크',
    pixelPitchOptions: ['24인치', '옵션'],
    description: '결제 및 주문을 위한 전문 키오스크 솔루션입니다.',
    specifications: {
      moduleSize: '다양한 크기 지원',
      moduleResolution: '1920 x 1080 (Full HD)',
      pixelDensity: '고해상도 디스플레이',
      optimalViewingDistance: 'Min 0.5m ~ Max 3m',
      screenBrightness: '250nit',
      pixelConfiguration: '1R1G1B',
      refreshRate: '3840Hz',
      viewingAngle: '160°/160°',
      flatness: '≤0.1mm',
      operatingTemperature: '-35°C to +50°C',
      operatingHumidity: '10% to +90%',
      ratedInput: 'AC 110~240V~(±10%)',
      maintenance: 'Front Maintenance (전면 유지보수)',
    },
    models: {
      '24인치': [
        {
          modelName: 'LH24KMATBGCXKR',
          resolution: '1920 x 1080',
          brightness: '250nit',
          size: '334 x 733 x 236',
          vesaHole: '-',
          price: '1,000,000원',
        },
      ],
      옵션: [
        {
          modelName: 'Floor Stand',
          resolution: '-',
          brightness: '-',
          size: '450 x 1650 x 325',
          vesaHole: '고정형 스탠드형',
          price: '400,000원',
          stock: '세트 구성품 (포스기 +주방프린터 +금전함 +키보드 +마우스)',
        },
        {
          modelName: '아임유 포스기세트',
          resolution: '-',
          brightness: '-',
          size: '포스기세트(IU)',
          vesaHole: '키오스크 부속품',
          price: '650,000원',
          stock: '옵션',
        },
        {
          modelName: '아임유 주방프린터',
          resolution: '-',
          brightness: '-',
          size: '주방프린터(IU)',
          vesaHole: '기본형 주방용 프린터',
          price: '85,000원',
          stock: '옵션',
        },
      ],
    },
  },
};

export default async function DigitalSignageDetailPage({
  params,
}: {
  params: Promise<{ district_id: string }>;
}) {
  const { district_id } = await params;
  const productData =
    productDataMap[district_id as keyof typeof productDataMap];

  if (!productData) {
    return <div>Product not found</div>;
  }

  // 디지털사이니지 아이템인지 확인
  const isDigitalSignageItem = [
    'samsung-single',
    'lg-single',
    'samsung-multivision',
    'samsung-chalkboard',
    'samsung-kiosk',
    'multivision-videowall',
    'aida-digital-frame',
    'stand-signage',
    'the-gallery',
    'q-series-stand',
    'q-series-touch',
    'outdoor-wall',
    'outdoor-stand',
    'led-display',
    'led-controller',
    'led-installation',
    'bracket',
    'electronic-whiteboard',
    'kiosk',
  ].includes(district_id);

  return (
    <DigitalSignageDetailClient
      productData={productData}
      isDigitalSignage={isDigitalSignageItem}
    />
  );
}
