-- ====================================
-- 디지털 제품 데이터 삽입 (전체 데이터)
-- ====================================

INSERT INTO public.digital_products (
  product_code, title, main_image_url, image_urls,
  product_type, series_name, model_name, brand,
  inch_size, physical_size, resolution, brightness,
  specifications, usage, installation_method, vesa_hole,
  price, special_features, description, bracket_note, contact_info,
  display_order, is_active
) VALUES
-- 삼성 싱글 사이니지 - QB Series
('samsung-qb-85', '삼성 QB 85인치 사이니지', '/images/digital-media/digital_signage/1_samsung_singleSignage.jpg', 
 ARRAY['/images/digital-media/digital_signage/1_samsung_singleSignage.jpg'], 
 '싱글 사이니지', 'QB Series', 'LH85QBRBDGCXKR', '삼성전자', '85인치', 
 '1897.8 x 1080.8 x 56.7', '3840 x 2160(4K UHD)', '350nit',
 'USB INPUT 제어 / 매직인포 네트워크 솔루션', 
 '광고, 홍보, 메뉴보드, 캠페인 등의 미디어 콘텐츠 송출',
 '벽면설치, 매립설치, 천정설치 등', '600 x 400', '2,300,000원',
 'SAMSUNG QB (4K, 350nit)', 
 '벽면 설치가 가능한 실내용 디지털 사이니지로, 대형 화면 시청이 가능하며 다양한 공간에 설치할 수 있습니다.',
 '※ 싱글사이니지 브라켓은 별도 문의', '02-711-3737', 1, true),

-- 삼성 싱글 사이니지 - QH Series
('samsung-single-qh-43', '삼성 QH 43인치', '/images/digital-media/digital_signage/1_samsung_singleSignage.jpg',
 ARRAY['/images/digital-media/digital_signage/1_samsung_singleSignage.jpg'],
 '싱글 사이니지(삼성)', 'QH Series', 'LH43QHBEBGCXKR', '삼성전자', '43인치',
 '967.5 x 557.7 x 48.3', '3,840 x 2160 (4K UHD)', '700nit',
 'USB INPUT 제어 / 매직인포 네트워크 솔루션',
 '광고, 홍보, 메뉴보드, 캠페인 등의 미디어 콘텐츠 송출',
 '벽면설치, 매립설치, 천정설치 등', '200 x 200', '611,000원',
 'Non-Glare 빛 반사 방지패널',
 '벽면 설치가 가능한 실내용 디지털 사이니지로, 대형 화면 시청이 가능하며 다양한 공간에 설치할 수 있습니다.',
 '※ 싱글사이니지 브라켓은 별도 문의', '02-711-3737', 2, true),

('samsung-single-qh-50', '삼성 QH 50인치', '/images/digital-media/digital_signage/1_samsung_singleSignage.jpg',
 ARRAY['/images/digital-media/digital_signage/1_samsung_singleSignage.jpg'],
 '싱글 사이니지(삼성)', 'QH Series', 'LH50QHBEBGCXKR', '삼성전자', '50인치',
 '1121.4 x 643.9 x 46.3', '3,840 x 2160 (4K UHD)', '700nit',
 'USB INPUT 제어 / 매직인포 네트워크 솔루션',
 '광고, 홍보, 메뉴보드, 캠페인 등의 미디어 콘텐츠 송출',
 '벽면설치, 매립설치, 천정설치 등', '200 x 200', '780,000원',
 'Non-Glare 빛 반사 방지패널',
 '벽면 설치가 가능한 실내용 디지털 사이니지로, 대형 화면 시청이 가능하며 다양한 공간에 설치할 수 있습니다.',
 '※ 싱글사이니지 브라켓은 별도 문의', '02-711-3737', 3, true),

('samsung-single-qh-75', '삼성 QH 75인치', '/images/digital-media/digital_signage/1_samsung_singleSignage.jpg',
 ARRAY['/images/digital-media/digital_signage/1_samsung_singleSignage.jpg'],
 '싱글 사이니지(삼성)', 'QH Series', 'LH75QHBEBGCXKR', '삼성전자', '75인치',
 '1681.1 x 960.1 x 49.7', '3,840 x 2160 (4K UHD)', '700nit',
 'USB INPUT 제어 / 매직인포 네트워크 솔루션',
 '광고, 홍보, 메뉴보드, 캠페인 등의 미디어 콘텐츠 송출',
 '벽면설치, 매립설치, 천정설치 등', '400 x 400', '1,651,000원',
 'Non-Glare 빛 반사 방지패널',
 '벽면 설치가 가능한 실내용 디지털 사이니지로, 대형 화면 시청이 가능하며 다양한 공간에 설치할 수 있습니다.',
 '※ 싱글사이니지 브라켓은 별도 문의', '02-711-3737', 4, true),

-- 삼성 싱글 사이니지 - QM Series
('samsung-single-qm-43', '삼성 QM 43인치', '/images/digital-media/digital_signage/1_samsung_singleSignage.jpg',
 ARRAY['/images/digital-media/digital_signage/1_samsung_singleSignage.jpg'],
 '싱글 사이니지(삼성)', 'QM Series', 'LH43QMBEBGCXKR', '삼성전자', '43인치',
 '967.5 x 557.7 x 48.3', '3,840 x 2160 (4K UHD)', '500nit',
 'USB INPUT 제어 / 매직인포 네트워크 솔루션',
 '광고, 홍보, 메뉴보드, 캠페인 등의 미디어 콘텐츠 송출',
 '벽면설치, 매립설치, 천정설치 등', '200 x 200', '526,000원',
 'Non-Glare 빛 반사 방지패널',
 '벽면 설치가 가능한 실내용 디지털 사이니지로, 대형 화면 시청이 가능하며 다양한 공간에 설치할 수 있습니다.',
 '※ 싱글사이니지 브라켓은 별도 문의', '02-711-3737', 5, true),

('samsung-single-qm-50', '삼성 QM 50인치', '/images/digital-media/digital_signage/1_samsung_singleSignage.jpg',
 ARRAY['/images/digital-media/digital_signage/1_samsung_singleSignage.jpg'],
 '싱글 사이니지(삼성)', 'QM Series', 'LH50QMBEBGCXKR', '삼성전자', '50인치',
 '1121.4 x 643.9 x 46.3', '3,840 x 2160 (4K UHD)', '500nit',
 'USB INPUT 제어 / 매직인포 네트워크 솔루션',
 '광고, 홍보, 메뉴보드, 캠페인 등의 미디어 콘텐츠 송출',
 '벽면설치, 매립설치, 천정설치 등', '200 x 200', '526,000원',
 'Non-Glare 빛 반사 방지패널',
 '벽면 설치가 가능한 실내용 디지털 사이니지로, 대형 화면 시청이 가능하며 다양한 공간에 설치할 수 있습니다.',
 '※ 싱글사이니지 브라켓은 별도 문의', '02-711-3737', 6, true),

('samsung-single-qm-75', '삼성 QM 75인치', '/images/digital-media/digital_signage/1_samsung_singleSignage.jpg',
 ARRAY['/images/digital-media/digital_signage/1_samsung_singleSignage.jpg'],
 '싱글 사이니지(삼성)', 'QM Series', 'LH75QMBEBGCXKR', '삼성전자', '75인치',
 '1681.1 x 960.1 x 49.7', '3,840 x 2160 (4K UHD)', '500nit',
 'USB INPUT 제어 / 매직인포 네트워크 솔루션',
 '광고, 홍보, 메뉴보드, 캠페인 등의 미디어 콘텐츠 송출',
 '벽면설치, 매립설치, 천정설치 등', '400 x 400', '1,541,000원',
 'Non-Glare 빛 반사 방지패널',
 '벽면 설치가 가능한 실내용 디지털 사이니지로, 대형 화면 시청이 가능하며 다양한 공간에 설치할 수 있습니다.',
 '※ 싱글사이니지 브라켓은 별도 문의', '02-711-3737', 7, true),

('samsung-single-qm-85', '삼성 QM 85인치', '/images/digital-media/digital_signage/1_samsung_singleSignage.jpg',
 ARRAY['/images/digital-media/digital_signage/1_samsung_singleSignage.jpg'],
 '싱글 사이니지(삼성)', 'QM Series', 'LH85QMRBBGCX/KR', '삼성전자', '85인치',
 '1897.8 x 1080.8 x 56.7', '3,840 x 2160 (4K UHD)', '500nit',
 'USB INPUT 제어 / 매직인포 네트워크 솔루션',
 '광고, 홍보, 메뉴보드, 캠페인 등의 미디어 콘텐츠 송출',
 '벽면설치, 매립설치, 천정설치 등', '600 x 400', '2,400,000원',
 'Non-Glare 빛 반사 방지패널',
 '벽면 설치가 가능한 실내용 디지털 사이니지로, 대형 화면 시청이 가능하며 다양한 공간에 설치할 수 있습니다.',
 '※ 싱글사이니지 브라켓은 별도 문의', '02-711-3737', 8, true),

-- LG 싱글 사이니지
('lg-55se3d', 'LG 55인치 사이니지', '/images/digital-media/digital_signage/4_LG_signage.jpg',
 ARRAY['/images/digital-media/digital_signage/4_LG_signage.jpg'],
 '싱글 사이니지', 'LG Series', '55SE3D-B', 'LG전자', '55인치',
 '1,238 x 714.9 x 38.6', '1,920 X 1,080', 'Max. 350cd/m²',
 'LG 사이니지 솔루션',
 '광고, 홍보, 메뉴보드, 캠페인 등의 미디어 콘텐츠 송출',
 '벽면설치, 매립설치, 천정설치 등', '300 x 300', '500,000원',
 'LG 고품질 디스플레이',
 'LG의 고품질 싱글 사이니지로, 다양한 공간에 설치 가능합니다.',
 NULL, '02-711-3737', 20, true),

-- 스탠드 사이니지
('stand-signage-43', '스탠드 사이니지 43인치', '/images/digital-media/digital_signage/5_chinese_standard.jpg',
 ARRAY['/images/digital-media/digital_signage/5_chinese_standard.jpg'],
 '스탠드 사이니지(수입)', 'Stand Series', 'DS430R-PT', '수입', '43인치',
 '599 x 1800 x 460 (발판)', '1,920 X 1,080', 'Max. 350cd/m²',
 '터치모니터',
 '광고, 홍보, 메뉴보드, 캠페인 등의 미디어 콘텐츠 송출',
 '스탠드 설치', '300 x 300', '상담문의',
 'PC 타입',
 '터치 기능이 있는 스탠드형 디지털 사이니지입니다.',
 NULL, '02-711-3737', 30, true),

-- 멀티비전(비디오월) - VW Series
('multivision-vw550e-5lw', '멀티비전 VW550E-5LW', '/images/digital-media/digital_signage/7_multiVision_1.jpg',
 ARRAY['/images/digital-media/digital_signage/7_multiVision_1.jpg', '/images/digital-media/digital_signage/7_multiVision_2.jpg', '/images/digital-media/digital_signage/7_multiVision_3.jpg'],
 '멀티비전', 'VW Series', 'VW550E-5LW', '주식회사 시스메이트', '55인치(2.6mm)',
 '1212.2 x 683 x 92.5', '1,920 x 1,080', '500nit',
 '경량 멀티비전',
 '로비, 관제실, 강당, 회의실 등의 공간에 대형 디스플레이 구축',
 '노출, 매립 및 수요자 제안에 따른 커스터마이징 전문 시공', '600 x 400', '1,434,000원',
 '베젤 규격: 2.6mm / 500nit, 무게: 19.6kg',
 '베젤리스 멀티형 모니터로 대형 디스플레이 구축에 최적화된 제품입니다.',
 NULL, '02-711-3737', 40, true),

('multivision-vw550e-7lw', '멀티비전 VW550E-7LW', '/images/digital-media/digital_signage/7_multiVision_1.jpg',
 ARRAY['/images/digital-media/digital_signage/7_multiVision_1.jpg', '/images/digital-media/digital_signage/7_multiVision_2.jpg', '/images/digital-media/digital_signage/7_multiVision_3.jpg'],
 '멀티비전(비디오월)', 'VW Series', 'VW550E-7LW', '주식회사 시스메이트', '55인치(2.6mm)',
 '1212.2 x 683 x 92.5', '1,920 x 1,080', '700nit',
 '경량 멀티비전',
 '로비, 관제실, 강당, 회의실 등의 공간에 대형 디스플레이 구축',
 '노출, 매립 및 수요자 제안에 따른 커스터마이징 전문 시공', '600 x 400', '1,640,000원',
 '베젤 규격: 2.6mm / 700nit, 무게: 19.7kg',
 '베젤리스 멀티형 모니터로 대형 디스플레이 구축에 최적화된 제품입니다.',
 NULL, '02-711-3737', 41, true),

('multivision-vw550r-5lw', '멀티비전 VW550R-5LW', '/images/digital-media/digital_signage/7_multiVision_1.jpg',
 ARRAY['/images/digital-media/digital_signage/7_multiVision_1.jpg', '/images/digital-media/digital_signage/7_multiVision_2.jpg', '/images/digital-media/digital_signage/7_multiVision_3.jpg'],
 '멀티비전(비디오월)', 'VW Series', 'VW550R-5LW', '주식회사 시스메이트', '55인치(0.88mm)',
 '1210.51 x 681.22 x 92.4', '1,920 x 1,080', '500nit',
 '경량 멀티비전',
 '로비, 관제실, 강당, 회의실 등의 공간에 대형 디스플레이 구축',
 '노출, 매립 및 수요자 제안에 따른 커스터마이징 전문 시공', '600 x 400', '1,840,000원',
 '베젤 규격: 0.88mm / 500nit, 무게: 18.5kg',
 '베젤리스 멀티형 모니터로 대형 디스플레이 구축에 최적화된 제품입니다.',
 NULL, '02-711-3737', 42, true),

('multivision-vw550r-7lw', '멀티비전 VW550R-7LW', '/images/digital-media/digital_signage/7_multiVision_1.jpg',
 ARRAY['/images/digital-media/digital_signage/7_multiVision_1.jpg', '/images/digital-media/digital_signage/7_multiVision_2.jpg', '/images/digital-media/digital_signage/7_multiVision_3.jpg'],
 '멀티비전(비디오월)', 'VW Series', 'VW550R-7LW', '주식회사 시스메이트', '55인치(0.88mm)',
 '1210.51 x 681.22 x 92.4', '1,920 x 1,080', '700nit',
 '경량 멀티비전',
 '로비, 관제실, 강당, 회의실 등의 공간에 대형 디스플레이 구축',
 '노출, 매립 및 수요자 제안에 따른 커스터마이징 전문 시공', '600 x 400', '2,021,000원',
 '베젤 규격: 0.88mm / 700nit, 무게: 18.1kg',
 '베젤리스 멀티형 모니터로 대형 디스플레이 구축에 최적화된 제품입니다.',
 NULL, '02-711-3737', 43, true),

-- 디지털액자
('digital-frame-10', '디지털액자 10인치', '/images/digital-media/digital_signage/8_AIDA_digitalFrame.jpg',
 ARRAY['/images/digital-media/digital_signage/8_AIDA_digitalFrame.jpg'],
 '디지털액자', 'Frame Series', 'AIDA 1004IPS', '주식회사 시스메이트', '10" (25.4cm)',
 '169 x 365 x 59', '800 x 1,280', '250nit',
 '미니 사이니지',
 '개인 소장용 사진 액자, 홍보용 전자액자, 메뉴보드 등',
 '스탠드 설치', '표준', '상담문의',
 '베젤 규격: 2.6mm (Bezel to Bezel), 디지털액자(콘텐츠), 지원형식: AVI, MP4, MP3, JPG, PNG 등',
 '개인 소장용 사진 액자, 홍보용 전자액자, 메뉴보드 등에 활용 가능한 미니 사이니지입니다.',
 NULL, '02-711-3737', 50, true),

-- 삼성 전자칠판
('samsung-board-55', '삼성 전자칠판 55인치', '/images/digital-media/digital_signage/3_samsung_digitalBoard.jpg',
 ARRAY['/images/digital-media/digital_signage/3_samsung_digitalBoard.jpg'],
 '삼성 전자칠판', 'Electronic Board Series', 'LH55WMBWBGCXKR', '삼성전자', '55인치',
 '1297.4 x 768.2 x 59.9 mm', '3,840 x 2,160 (4K UHD)', '350nit',
 '삼성 판서솔루션, 외부장치 연결(모니터 활용), 자체 웹 뷰잉',
 '교육, 강의, 회의, 컨퍼런스 등의 스마트 프리젠테이션 활용',
 '벽면설치, 이동형 스탠드 설치 등', '400 x 400', '상담문의',
 '함체 색상: 화이트, 명암비: 4,000 : 1, 옵션사항: 벽부형 브라켓, 이동형 스탠드, 확장형 포트',
 '교육, 강의, 회의, 컨퍼런스 등의 스마트 프리젠테이션 활용에 최적화된 전자칠판입니다.',
 NULL, '02-711-3737', 60, true),

-- 삼성 결제키오스크
('samsung-kiosk', '삼성 결제키오스크', '/images/digital-media/digital_signage/6_samsung_paymentKiosk.jpg',
 ARRAY['/images/digital-media/digital_signage/6_samsung_paymentKiosk.jpg'],
 '결제키오스크(삼성)', 'Kiosk Series', '삼성 결제키오스크', '삼성전자', '표준',
 '제품문의', '제품문의', '제품문의',
 '결제키오스크',
 '결제, 주문, 안내 등의 키오스크 용도',
 '스탠드 설치', 'N/A', '상담문의',
 '결제키오스크',
 '삼성전자 결제키오스크 제품입니다.',
 NULL, '02-711-3737', 100, true),

-- 멀티비전 VW550R 경량2 시리즈
('multivision-vw550r-5lw-light2', '멀티비전 VW550R-5LW 경량2', '/images/digital-media/digital_signage/7_multiVision_1.jpg',
 ARRAY['/images/digital-media/digital_signage/7_multiVision_1.jpg', '/images/digital-media/digital_signage/7_multiVision_2.jpg', '/images/digital-media/digital_signage/7_multiVision_3.jpg'],
 '멀티비전(비디오월)', 'VW Series', 'VW550R-5LW_경량2', '주식회사 시스메이트', '55인치(0.88mm)',
 '1210.51 x 681.22 x 92.4', '1,920 x 1,080', '500nit',
 '경량 멀티비전',
 '로비, 관제실, 강당, 회의실 등의 공간에 대형 디스플레이 구축',
 '노출, 매립 및 수요자 제안에 따른 커스터마이징 전문 시공', '600 x 400', '1,700,000원',
 '베젤 규격: 0.88mm / 500nit, 매그놀리아, 무게: 별도 문의',
 '베젤리스 멀티형 모니터로 대형 디스플레이 구축에 최적화된 제품입니다.',
 NULL, '02-711-3737', 44, true),

('multivision-vw550r-7lw-light2', '멀티비전 VW550R-7LW 경량2', '/images/digital-media/digital_signage/7_multiVision_1.jpg',
 ARRAY['/images/digital-media/digital_signage/7_multiVision_1.jpg', '/images/digital-media/digital_signage/7_multiVision_2.jpg', '/images/digital-media/digital_signage/7_multiVision_3.jpg'],
 '멀티비전(비디오월)', 'VW Series', 'VW550R-7LW_경량2', '주식회사 시스메이트', '55인치(0.88mm)',
 '1210.51 x 681.22 x 92.4', '1,920 x 1,080', '700nit',
 '경량 멀티비전',
 '로비, 관제실, 강당, 회의실 등의 공간에 대형 디스플레이 구축',
 '노출, 매립 및 수요자 제안에 따른 커스터마이징 전문 시공', '600 x 400', '1,870,000원',
 '베젤 규격: 0.88mm / 700nit, 매그놀리아',
 '베젤리스 멀티형 모니터로 대형 디스플레이 구축에 최적화된 제품입니다.',
 NULL, '02-711-3737', 45, true),

-- 삼성 전자칠판 트레이
('samsung-board-tray-65', '삼성 전자칠판 트레이 65인치', '/images/digital-media/digital_signage/3_samsung_digitalBoard.jpg',
 ARRAY['/images/digital-media/digital_signage/3_samsung_digitalBoard.jpg'],
 '삼성 전자칠판 트레이', 'Tray Series', 'CY-TF65BRCXKR', '삼성전자', '65인치',
 '269.8 x 111.3 x 56.9', 'N/A', 'N/A',
 '삼성 전자칠판 트레이',
 '삼성 전자칠판용 트레이',
 '전자칠판 부착', 'N/A', '상담문의',
 '전자칠판 트레이',
 '삼성 전자칠판용 트레이 제품입니다.',
 NULL, '02-711-3737', 61, true),

-- 삼성 전자칠판 브라켓
('samsung-board-bracket-5565', '삼성 전자칠판 브라켓 55/65형', '/images/digital-media/digital_signage/3_samsung_digitalBoard.jpg',
 ARRAY['/images/digital-media/digital_signage/3_samsung_digitalBoard.jpg'],
 '삼성 전자칠판 브라켓', 'Bracket Series', '브라켓_HA-AF-STAND-BK (Flip 55형/65형)', '삼성전자', '55인치/65인치',
 '1000 x 1714 x 500', 'N/A', 'N/A',
 'Flip 55"/65" 스탠드 브라켓',
 '삼성 전자칠판용 스탠드 브라켓',
 '스탠드 설치', '600 x 400', '상담문의',
 'Flip 55"/65" 스탠드 브라켓',
 '삼성 전자칠판용 브라켓 제품들입니다.',
 NULL, '02-711-3737', 62, true),

('samsung-board-bracket-7585', '삼성 전자칠판 브라켓 75/85형', '/images/digital-media/digital_signage/3_samsung_digitalBoard.jpg',
 ARRAY['/images/digital-media/digital_signage/3_samsung_digitalBoard.jpg'],
 '삼성 전자칠판 브라켓', 'Bracket Series', '브라켓_HA-AFN-S7585-WH (Flip 75형/85형)', '삼성전자', '75인치/85인치',
 '1000 x 1714 x 500', 'N/A', 'N/A',
 'Flip 75"/85" 스탠드 브라켓',
 '삼성 전자칠판용 스탠드 브라켓',
 '스탠드 설치', '400 x 400', '상담문의',
 'Flip 75"/85" 스탠드 브라켓',
 '삼성 전자칠판용 브라켓 제품들입니다.',
 NULL, '02-711-3737', 63, true),

('samsung-board-bracket-65-wall', '삼성 전자칠판 브라켓 65형 벽걸이', '/images/digital-media/digital_signage/3_samsung_digitalBoard.jpg',
 ARRAY['/images/digital-media/digital_signage/3_samsung_digitalBoard.jpg'],
 '삼성 전자칠판 브라켓', 'Bracket Series', '브라켓_삼성 WMN-WM65RXKR', '삼성전자', '65인치',
 '1000 x 1714 x 500', 'N/A', 'N/A',
 'Flip Pro 65" 벽걸이 브라켓',
 '삼성 전자칠판용 벽걸이 브라켓',
 '벽면설치', '400 x 400', '상담문의',
 'Flip Pro 65" 벽걸이 브라켓',
 '삼성 전자칠판용 브라켓 제품들입니다.',
 NULL, '02-711-3737', 64, true),

-- 삼성 멀티비전
('samsung-multivision-vw550e-5lw', '삼성 멀티비전 VW550E-5LW', '/images/digital-media/digital_signage/2_samsung_multiVision.jpg',
 ARRAY['/images/digital-media/digital_signage/2_samsung_multiVision.jpg'],
 '삼성 멀티비전', 'Samsung Multivision Series', 'VW550E-5LW', '삼성전자', '55인치',
 '1211.0 x 681.7 x 69.9', '1,920 x 1,080 (FULL HD)', '700nit',
 '베젤리스 멀티형 모니터',
 '로비, 관제실, 강당, 회의실 등의 공간에 대형 디스플레이 구축',
 '노출, 매립 및 수요자 제안에 따른 커스터마이징 전문 시공', '600 x 400', '상담문의',
 '원격 제어용 네트워크 솔루션, 다중 매트릭스 장비 등',
 '베젤리스 멀티형 모니터로 대형 디스플레이 구축에 최적화된 삼성 제품입니다.',
 NULL, '02-711-3737', 70, true),

('samsung-multivision-vw550e-7lw', '삼성 멀티비전 VW550E-7LW', '/images/digital-media/digital_signage/2_samsung_multiVision.jpg',
 ARRAY['/images/digital-media/digital_signage/2_samsung_multiVision.jpg'],
 '삼성 멀티비전', 'Samsung Multivision Series', 'VW550E-7LW', '삼성전자', '55인치',
 '1211.0 x 681.7 x 69.9', '1,920 x 1,080 (FULL HD)', '500nit',
 '베젤리스 멀티형 모니터',
 '로비, 관제실, 강당, 회의실 등의 공간에 대형 디스플레이 구축',
 '노출, 매립 및 수요자 제안에 따른 커스터마이징 전문 시공', '600 x 400', '상담문의',
 '원격 제어용 네트워크 솔루션, 다중 매트릭스 장비 등',
 '베젤리스 멀티형 모니터로 대형 디스플레이 구축에 최적화된 삼성 제품입니다.',
 NULL, '02-711-3737', 71, true),

('samsung-multivision-vw550r-5lw', '삼성 멀티비전 VW550R-5LW', '/images/digital-media/digital_signage/2_samsung_multiVision.jpg',
 ARRAY['/images/digital-media/digital_signage/2_samsung_multiVision.jpg'],
 '삼성 멀티비전', 'Samsung Multivision Series', 'VW550R-5LW', '삼성전자', '55인치',
 '1211.0 x 681.7 x 69.9', '1,920 x 1,080 (FULL HD)', '500nit',
 '베젤리스 멀티형 모니터',
 '로비, 관제실, 강당, 회의실 등의 공간에 대형 디스플레이 구축',
 '노출, 매립 및 수요자 제안에 따른 커스터마이징 전문 시공', '600 x 400', '상담문의',
 '원격 제어용 네트워크 솔루션, 다중 매트릭스 장비 등',
 '베젤리스 멀티형 모니터로 대형 디스플레이 구축에 최적화된 삼성 제품입니다.',
 NULL, '02-711-3737', 72, true),

-- 더 갤러리 - QB Series
('the-gallery-qb43', '더 갤러리 QB43F', '/images/digital-media/digital_signage/10_theGallery.png',
 ARRAY['/images/digital-media/digital_signage/10_theGallery.png'],
 '더 갤러리', 'QB Series', 'QB43F_WTE', '삼성전자', '43인치',
 '978.8 x 567 x 37', '3,840 x 2,160', '350cd/m²',
 'USB INPUT 제어 / 매직인포 네트워크 솔루션',
 '광고, 홍보, 메뉴보드, 캠페인 등의 미디어 콘텐츠 송출',
 '벽면설치, 매립설치, 천정설치 등', '200 x 200', '상담문의',
 '액자형 사이니지, 프레임 색상: 화이트, 옵션 사항: 명화 콘텐츠',
 '액자형 사이니지로 명화 콘텐츠를 지원하는 고품질 디스플레이입니다.',
 NULL, '02-711-3737', 80, true),

('the-gallery-qb50', '더 갤러리 QB50F', '/images/digital-media/digital_signage/10_theGallery.png',
 ARRAY['/images/digital-media/digital_signage/10_theGallery.png'],
 '더 갤러리', 'QB Series', 'QB50F_WTE', '삼성전자', '50인치',
 '1133.3 x 654 x 37', '3,840 x 2,160', '350cd/m²',
 'USB INPUT 제어 / 매직인포 네트워크 솔루션',
 '광고, 홍보, 메뉴보드, 캠페인 등의 미디어 콘텐츠 송출',
 '벽면설치, 매립설치, 천정설치 등', '200 x 200', '상담문의',
 '액자형 사이니지, 프레임 색상: 화이트, 옵션 사항: 명화 콘텐츠',
 '액자형 사이니지로 명화 콘텐츠를 지원하는 고품질 디스플레이입니다.',
 NULL, '02-711-3737', 81, true),

('the-gallery-qb55', '더 갤러리 55인치', '/images/digital-media/digital_signage/10_theGallery.png',
 ARRAY['/images/digital-media/digital_signage/10_theGallery.png'],
 '더 갤러리', 'QB Series', 'LH85QBRBDGCXKR', '삼성전자', '55인치',
 '1247.2 x 718 x 37', '3,840 x 2,160', '350cd/m²',
 'USB INPUT 제어 / 매직인포 네트워크 솔루션',
 '광고, 홍보, 메뉴보드, 캠페인 등의 미디어 콘텐츠 송출',
 '벽면설치, 매립설치, 천정설치 등', '200 x 200', '상담문의',
 '액자형 사이니지, 프레임 색상: 화이트, 옵션 사항: 명화 콘텐츠',
 '액자형 사이니지로 명화 콘텐츠를 지원하는 고품질 디스플레이입니다.',
 NULL, '02-711-3737', 82, true),

('the-gallery-qb65', '더 갤러리 QB65F', '/images/digital-media/digital_signage/10_theGallery.png',
 ARRAY['/images/digital-media/digital_signage/10_theGallery.png'],
 '더 갤러리', 'QB Series', 'QB65F_WTE', '삼성전자', '65인치',
 '978.8 x 567 x 37', '3,840 x 2,160', '350cd/m²',
 'USB INPUT 제어 / 매직인포 네트워크 솔루션',
 '광고, 홍보, 메뉴보드, 캠페인 등의 미디어 콘텐츠 송출',
 '벽면설치, 매립설치, 천정설치 등', '200 x 200', '상담문의',
 '액자형 사이니지, 프레임 색상: 화이트, 옵션 사항: 명화 콘텐츠',
 '액자형 사이니지로 명화 콘텐츠를 지원하는 고품질 디스플레이입니다.',
 NULL, '02-711-3737', 83, true),

-- 더 갤러리 - QM Series
('the-gallery-qm43', '더 갤러리 QM43F', '/images/digital-media/digital_signage/10_theGallery.png',
 ARRAY['/images/digital-media/digital_signage/10_theGallery.png'],
 '더 갤러리', 'QM Series', 'QM43F_WTE', '삼성전자', '43인치',
 '978.8 x 567 x 37', '3,840 x 2,160', '500cd/m²',
 'USB INPUT 제어 / 매직인포 네트워크 솔루션',
 '광고, 홍보, 메뉴보드, 캠페인 등의 미디어 콘텐츠 송출',
 '벽면설치, 매립설치, 천정설치 등', '200 x 200', '상담문의',
 '액자형 사이니지, 프레임 색상: 화이트, 옵션 사항: 명화 콘텐츠',
 '액자형 사이니지로 명화 콘텐츠를 지원하는 고품질 디스플레이입니다.',
 NULL, '02-711-3737', 84, true),

('the-gallery-qm50', '더 갤러리 QM50F', '/images/digital-media/digital_signage/10_theGallery.png',
 ARRAY['/images/digital-media/digital_signage/10_theGallery.png'],
 '더 갤러리', 'QM Series', 'QM50F_WTE', '삼성전자', '50인치',
 '1133.3 x 654 x 37', '3,840 x 2,160', '500cd/m²',
 'USB INPUT 제어 / 매직인포 네트워크 솔루션',
 '광고, 홍보, 메뉴보드, 캠페인 등의 미디어 콘텐츠 송출',
 '벽면설치, 매립설치, 천정설치 등', '200 x 200', '상담문의',
 '액자형 사이니지, 프레임 색상: 화이트, 옵션 사항: 명화 콘텐츠',
 '액자형 사이니지로 명화 콘텐츠를 지원하는 고품질 디스플레이입니다.',
 NULL, '02-711-3737', 85, true),

('the-gallery-qm55', '더 갤러리 QM55F', '/images/digital-media/digital_signage/10_theGallery.png',
 ARRAY['/images/digital-media/digital_signage/10_theGallery.png'],
 '더 갤러리', 'QM Series', 'QM55F_WTE', '삼성전자', '55인치',
 '1247.2 x 718 x 37', '3,840 x 2,160', '500cd/m²',
 'USB INPUT 제어 / 매직인포 네트워크 솔루션',
 '광고, 홍보, 메뉴보드, 캠페인 등의 미디어 콘텐츠 송출',
 '벽면설치, 매립설치, 천정설치 등', '200 x 200', '상담문의',
 '액자형 사이니지, 프레임 색상: 화이트, 옵션 사항: 명화 콘텐츠',
 '액자형 사이니지로 명화 콘텐츠를 지원하는 고품질 디스플레이입니다.',
 NULL, '02-711-3737', 86, true),

('the-gallery-qm65', '더 갤러리 QM65F', '/images/digital-media/digital_signage/10_theGallery.png',
 ARRAY['/images/digital-media/digital_signage/10_theGallery.png'],
 '더 갤러리', 'QM Series', 'QM65F_WTE', '삼성전자', '65인치',
 '978.8 x 567 x 37', '3,840 x 2,160', '500cd/m²',
 'USB INPUT 제어 / 매직인포 네트워크 솔루션',
 '광고, 홍보, 메뉴보드, 캠페인 등의 미디어 콘텐츠 송출',
 '벽면설치, 매립설치, 천정설치 등', '200 x 200', '상담문의',
 '액자형 사이니지, 프레임 색상: 화이트, 옵션 사항: 명화 콘텐츠',
 '액자형 사이니지로 명화 콘텐츠를 지원하는 고품질 디스플레이입니다.',
 NULL, '02-711-3737', 87, true),

-- Q시리즈 스탠드 사이니지
('q-series-stand-43', 'Q시리즈 스탠드 43인치', '/images/digital-media/digital_signage/9_standardSignage_pivot.jpg',
 ARRAY['/images/digital-media/digital_signage/9_standardSignage_pivot.jpg'],
 'Q시리즈 스탠드 사이니지', 'QB STAND BASIC', 'QH43F_WTE', '주식회사 시스메이트 / 삼성전자', '43인치',
 '585 x 1900 x 497.6', '3,840 x 2,160 (4K UHD)', '350nit',
 'Non-Glass',
 '광고, 홍보, 메뉴보드, 캠페인 등의 미디어 콘텐츠 송출',
 '스탠드 설치', '200 x 200', '상담문의',
 '제품 색상: 블랙 / 화이트, 기본기능: USB INPUT 미디어 콘텐츠 송출방식, 옵션기능: 네트워크 제어형, 터치센서',
 'Q시리즈 스탠드 사이니지 제품들입니다.',
 NULL, '02-711-3737', 90, true),

('q-series-stand-50', 'Q시리즈 스탠드 50인치', '/images/digital-media/digital_signage/9_standardSignage_pivot.jpg',
 ARRAY['/images/digital-media/digital_signage/9_standardSignage_pivot.jpg'],
 'Q시리즈 스탠드 사이니지', 'QB STAND BASIC', 'QH50F_WTE', '주식회사 시스메이트 / 삼성전자', '50인치',
 '691 x 1900 x 497.6', '3,840 x 2,160 (4K UHD)', '350nit',
 'Non-Glass',
 '광고, 홍보, 메뉴보드, 캠페인 등의 미디어 콘텐츠 송출',
 '스탠드 설치', '200 x 200', '상담문의',
 '제품 색상: 블랙 / 화이트, 기본기능: USB INPUT 미디어 콘텐츠 송출방식, 옵션기능: 네트워크 제어형, 터치센서',
 'Q시리즈 스탠드 사이니지 제품들입니다.',
 NULL, '02-711-3737', 91, true),

('q-series-stand-55', 'Q시리즈 스탠드 55인치', '/images/digital-media/digital_signage/9_standardSignage_pivot.jpg',
 ARRAY['/images/digital-media/digital_signage/9_standardSignage_pivot.jpg'],
 'Q시리즈 스탠드 사이니지', 'QB STAND BASIC', 'QH55F_WTE', '주식회사 시스메이트 / 삼성전자', '55인치',
 '740 x 1900 x 497.6', '3,840 x 2,160 (4K UHD)', '350nit',
 'Non-Glass',
 '광고, 홍보, 메뉴보드, 캠페인 등의 미디어 콘텐츠 송출',
 '스탠드 설치', '200 x 200', '상담문의',
 '제품 색상: 블랙 / 화이트, 기본기능: USB INPUT 미디어 콘텐츠 송출방식, 옵션기능: 네트워크 제어형, 터치센서',
 'Q시리즈 스탠드 사이니지 제품들입니다.',
 NULL, '02-711-3737', 92, true),

('q-series-stand-65', 'Q시리즈 스탠드 65인치', '/images/digital-media/digital_signage/9_standardSignage_pivot.jpg',
 ARRAY['/images/digital-media/digital_signage/9_standardSignage_pivot.jpg'],
 'Q시리즈 스탠드 사이니지', 'QB STAND BASIC', 'QB650CSB', '주식회사 시스메이트 / 삼성전자', '65인치',
 '900 x 1940 x 497.6', '3,840 x 2,160 (4K UHD)', '350nit',
 'Non-Glass',
 '광고, 홍보, 메뉴보드, 캠페인 등의 미디어 콘텐츠 송출',
 '스탠드 설치', '400 x 400', '상담문의',
 '제품 색상: 블랙 / 화이트, 기본기능: USB INPUT 미디어 콘텐츠 송출방식, 옵션기능: 네트워크 제어형, 터치센서',
 'Q시리즈 스탠드 사이니지 제품들입니다.',
 NULL, '02-711-3737', 93, true),

('q-series-stand-75', 'Q시리즈 스탠드 75인치', '/images/digital-media/digital_signage/9_standardSignage_pivot.jpg',
 ARRAY['/images/digital-media/digital_signage/9_standardSignage_pivot.jpg'],
 'Q시리즈 스탠드 사이니지', 'QB STAND BASIC', 'QB750CSB', '주식회사 시스메이트 / 삼성전자', '75인치',
 '1015 x 2090 x 560', '3,840 x 2,160 (4K UHD)', '350nit',
 'Non-Glass',
 '광고, 홍보, 메뉴보드, 캠페인 등의 미디어 콘텐츠 송출',
 '스탠드 설치', '400 x 400', '상담문의',
 '제품 색상: 블랙 / 화이트, 기본기능: USB INPUT 미디어 콘텐츠 송출방식, 옵션기능: 네트워크 제어형, 터치센서',
 'Q시리즈 스탠드 사이니지 제품들입니다.',
 NULL, '02-711-3737', 94, true),

-- Q시리즈 터치모니터
('q-series-touch-43', 'Q시리즈 터치모니터 43인치', '/images/digital-media/digital_signage/12_Qseries_touchMonitor.jpg',
 ARRAY['/images/digital-media/digital_signage/12_Qseries_touchMonitor.jpg'],
 'Q시리즈 터치모니터', 'QB IR 오버레이', 'QB43C_IR', '주식회사 시스메이트 / 삼성전자', '43인치',
 '1008 x 596.4 x 50', '3,840 x 2,160 (4K UHD)', '350nit',
 '터치모니터',
 '터치모니터, PC 등의 외부장치 연결',
 '벽면설치, 이동형 스탠드 외', '200 x 200', '상담문의',
 '주요기능: 외부장치 터치모니터 연결, 자체 웹 뷰잉, 광고 콘텐츠 송출, 핵심분류: 터치 디스플레이',
 'Q시리즈 터치모니터 제품들입니다.',
 NULL, '02-711-3737', 110, true),

('q-series-touch-50', 'Q시리즈 터치모니터 50인치', '/images/digital-media/digital_signage/12_Qseries_touchMonitor.jpg',
 ARRAY['/images/digital-media/digital_signage/12_Qseries_touchMonitor.jpg'],
 'Q시리즈 터치모니터', 'QB IR 오버레이', 'QB50C_IR', '주식회사 시스메이트 / 삼성전자', '50인치',
 '1173 x 686.3 x 50', '3,840 x 2,160 (4K UHD)', '350nit',
 '터치모니터',
 '터치모니터, PC 등의 외부장치 연결',
 '벽면설치, 이동형 스탠드 외', '200 x 200', '상담문의',
 '주요기능: 외부장치 터치모니터 연결, 자체 웹 뷰잉, 광고 콘텐츠 송출, 핵심분류: 터치 디스플레이',
 'Q시리즈 터치모니터 제품들입니다.',
 NULL, '02-711-3737', 111, true),

('q-series-touch-55', 'Q시리즈 터치모니터 55인치', '/images/digital-media/digital_signage/12_Qseries_touchMonitor.jpg',
 ARRAY['/images/digital-media/digital_signage/12_Qseries_touchMonitor.jpg'],
 'Q시리즈 터치모니터', 'QB IR 오버레이', 'QB55C_IR', '주식회사 시스메이트 / 삼성전자', '55인치',
 '1279 x 751 x 50', '3,840 x 2,160 (4K UHD)', '350nit',
 '터치모니터',
 '터치모니터, PC 등의 외부장치 연결',
 '벽면설치, 이동형 스탠드 외', '200 x 200', '상담문의',
 '주요기능: 외부장치 터치모니터 연결, 자체 웹 뷰잉, 광고 콘텐츠 송출, 핵심분류: 터치 디스플레이',
 'Q시리즈 터치모니터 제품들입니다.',
 NULL, '02-711-3737', 112, true),

-- 브라켓
('bracket-nsv-01', '브라켓 NSV-01', '/images/digital-media/digital_signage/13_bracket_NSV-01.jpg',
 ARRAY['/images/digital-media/digital_signage/13_bracket_NSV-01.jpg', '/images/digital-media/digital_signage/13_bracket_PV-70.jpg'],
 '브라켓', 'Bracket Series', 'NSV-01', '주식회사 시스메이트', '32인치 ~ 70인치',
 '제품문의', 'N/A', 'N/A',
 '멀티비전 유압식 팝업 브라켓',
 '멀티비전 및 모니터, TV 벽면 매립/노출 설치',
 '벽면설치', '최소200 x 200 / 최대 600 x 400', '상담문의',
 '제품분류: 벽부 팝업 브라켓 (유압식), 최대 하중: 45kg',
 '다양한 브라켓 제품들입니다.',
 NULL, '02-711-3737', 120, true),

('bracket-pv-70', '브라켓 PV-70', '/images/digital-media/digital_signage/13_bracket_PV-70.jpg',
 ARRAY['/images/digital-media/digital_signage/13_bracket_NSV-01.jpg', '/images/digital-media/digital_signage/13_bracket_PV-70.jpg'],
 '브라켓', 'Bracket Series', 'PV-70', '주식회사 시스메이트', '98인치',
 '제품문의', 'N/A', 'N/A',
 '대형 브라켓',
 '멀티비전 및 모니터, TV 벽면 매립/노출 설치',
 '벽면설치', '최소 200 x 200 / 최대 1200 x 600', '상담문의',
 '제품분류: 대형 브라켓 (98인치 설치가능), 최대 하중: 200kg',
 '다양한 브라켓 제품들입니다.',
 NULL, '02-711-3737', 121, true),

-- 옥외형 벽부타입
('outdoor-wall-550', '옥외형 벽부타입 55인치', '/images/digital-media/digital_signage/14_outdoor_wallType.jpg',
 ARRAY['/images/digital-media/digital_signage/14_outdoor_wallType.jpg', '/images/digital-media/digital_signage/14_outdoor_standard2.png'],
 '옥외형 벽부타입', 'Outdoor Wall Series', 'ODW550P', '주식회사 시스메이트', '55인치',
 '1410 x 1023.8 x 270', '1,920 x 1,080 (FHD)', '2500nit',
 '터치모니터',
 '옥외광고, 홍보, 캠페인 등의 미디어 콘텐츠 송출',
 '실내/실외 벽걸이 설치', '표준', '상담문의',
 '제품색상: 진 그레이, 운영방식: PC 내장형 네트워크 제어, 특수기능: 방수/방진, 야외 설치용 모델',
 '옥외용 벽부형 디스플레이입니다.',
 NULL, '02-711-3737', 130, true),

('outdoor-wall-750', '옥외형 벽부타입 75인치', '/images/digital-media/digital_signage/14_outdoor_wallType.jpg',
 ARRAY['/images/digital-media/digital_signage/14_outdoor_wallType.jpg', '/images/digital-media/digital_signage/14_outdoor_standard2.png'],
 '옥외형 벽부타입', 'Outdoor Wall Series', 'ODW750P', '주식회사 시스메이트', '75인치',
 '1850 x 1270 x 270', '3,840 x 2,160 (4K UHD)', '3000nit',
 '터치모니터',
 '옥외광고, 홍보, 캠페인 등의 미디어 콘텐츠 송출',
 '실내/실외 벽걸이 설치', '표준', '상담문의',
 '제품색상: 진 그레이, 운영방식: PC 내장형 네트워크 제어, 특수기능: 방수/방진, 야외 설치용 모델',
 '옥외용 벽부형 디스플레이입니다.',
 NULL, '02-711-3737', 131, true),

-- 옥외형 스탠드타입
('outdoor-stand-550', '옥외형 스탠드타입 55인치', '/images/digital-media/digital_signage/15_outdoor_standard2.jpg',
 ARRAY['/images/digital-media/digital_signage/15_outdoor_standard2.jpg'],
 '옥외형 스탠드타입', 'Outdoor Stand Series', 'ODS550P', '주식회사 시스메이트', '55인치',
 '860 x 1970 x 500 (발판)', '1,920 x 1,080 (FHD)', '2500nit',
 '터치모니터',
 '옥외광고, 홍보, 캠페인 등의 미디어 콘텐츠 송출',
 '실내/실외 자립 스탠드 고정 설치', '표준', '상담문의',
 '제품색상: 진 그레이, 운영방식: PC 내장형 네트워크 제어, 특수기능: 방수/방진, 야외 설치용 모델',
 '옥외용 스탠드형 디스플레이입니다.',
 NULL, '02-711-3737', 140, true),

('outdoor-stand-750', '옥외형 스탠드타입 75인치', '/images/digital-media/digital_signage/15_outdoor_standard2.jpg',
 ARRAY['/images/digital-media/digital_signage/15_outdoor_standard2.jpg'],
 '옥외형 스탠드타입', 'Outdoor Stand Series', 'ODS750P', '주식회사 시스메이트', '75인치',
 '1140 x 2200 x 600 (발판)', '3,840 x 2,160 (UHD)', '3000nit',
 '터치모니터',
 '옥외광고, 홍보, 캠페인 등의 미디어 콘텐츠 송출',
 '실내/실외 자립 스탠드 고정 설치', '표준', '상담문의',
 '제품색상: 진 그레이, 운영방식: PC 내장형 네트워크 제어, 특수기능: 방수/방진, 야외 설치용 모델',
 '옥외용 스탠드형 디스플레이입니다.',
 NULL, '02-711-3737', 141, true),

-- LED 디스플레이
('led-display-sm125h', 'LED 디스플레이 SM-125H', '/images/digital-media/digital_signage/16_LEDdisplay.jpg',
 ARRAY['/images/digital-media/digital_signage/16_LEDdisplay.jpg'],
 'LED 디스플레이 시리즈', 'LED 캐비닛', 'SM-125H', '주식회사 시스메이트', '27인치',
 '제품문의', '제품문의', '제품문의',
 '실내 / 실외대형 디스플레이 구축용 LED 전광판',
 '공공장소의 광고, 홍보, 안내 및 세미나/대강당 회의용 대형 전광판',
 '노출, 매립 및 수요자 제안에 따른 커스터마이징 전문 시공', 'N/A', '상담문의',
 'LED 캐비닛',
 '실내/실외 대형 디스플레이 구축용 LED 전광판입니다.',
 NULL, '02-711-3737', 150, true),

('led-display-sm156h', 'LED 디스플레이 SM-156H', '/images/digital-media/digital_signage/16_LEDdisplay.jpg',
 ARRAY['/images/digital-media/digital_signage/16_LEDdisplay.jpg'],
 'LED 디스플레이 시리즈', 'LED 캐비닛', 'SM-156H', '주식회사 시스메이트', '27.1인치',
 '제품문의', '제품문의', '제품문의',
 '실내 / 실외대형 디스플레이 구축용 LED 전광판',
 '공공장소의 광고, 홍보, 안내 및 세미나/대강당 회의용 대형 전광판',
 '노출, 매립 및 수요자 제안에 따른 커스터마이징 전문 시공', 'N/A', '상담문의',
 'LED 캐비닛',
 '실내/실외 대형 디스플레이 구축용 LED 전광판입니다.',
 NULL, '02-711-3737', 151, true),

('led-display-sm187h', 'LED 디스플레이 SM-187H', '/images/digital-media/digital_signage/16_LEDdisplay.jpg',
 ARRAY['/images/digital-media/digital_signage/16_LEDdisplay.jpg'],
 'LED 디스플레이 시리즈', 'LED 캐비닛', 'SM-187H', '주식회사 시스메이트', '27.1인치',
 '제품문의', '제품문의', '제품문의',
 '실내 / 실외대형 디스플레이 구축용 LED 전광판',
 '공공장소의 광고, 홍보, 안내 및 세미나/대강당 회의용 대형 전광판',
 '노출, 매립 및 수요자 제안에 따른 커스터마이징 전문 시공', 'N/A', '상담문의',
 'LED 캐비닛',
 '실내/실외 대형 디스플레이 구축용 LED 전광판입니다.',
 NULL, '02-711-3737', 152, true),

('led-display-sm250h', 'LED 디스플레이 SM-250H', '/images/digital-media/digital_signage/16_LEDdisplay.jpg',
 ARRAY['/images/digital-media/digital_signage/16_LEDdisplay.jpg'],
 'LED 디스플레이 시리즈', 'LED 캐비닛', 'SM-250H', '주식회사 시스메이트', '26.7인치',
 '978.8 x 567 x 37', '제품문의', '제품문의',
 '실내 / 실외대형 디스플레이 구축용 LED 전광판',
 '공공장소의 광고, 홍보, 안내 및 세미나/대강당 회의용 대형 전광판',
 '노출, 매립 및 수요자 제안에 따른 커스터마이징 전문 시공', 'N/A', '상담문의',
 'LED 캐비닛',
 '실내/실외 대형 디스플레이 구축용 LED 전광판입니다.',
 NULL, '02-711-3737', 153, true),

-- LED 컨트롤러
('led-controller-pc', 'LED 컨트롤러 PC형', '/images/digital-media/digital_signage/17-1-controller_PC.jpg',
 ARRAY['/images/digital-media/digital_signage/17-1-controller_PC.jpg', '/images/digital-media/digital_signage/17-2_controller_HD.jpg', '/images/digital-media/digital_signage/17-3-controller_FHD.jpg', '/images/digital-media/digital_signage/17-4_controller_FHD.jpg'],
 'LED 디스플레이 컨트롤러', 'LED Controller Series', 'PC형', '주식회사 시스메이트', 'N/A',
 'N/A', 'N/A', 'N/A',
 '컨트롤러 PC형',
 'LED 디스플레이 제어',
 'N/A', 'N/A', '상담문의',
 'LED 컨트롤러',
 'LED 디스플레이용 컨트롤러 제품들입니다.',
 NULL, '02-711-3737', 160, true),

('led-controller-hd', 'LED 컨트롤러 HD용', '/images/digital-media/digital_signage/17-2_controller_HD.jpg',
 ARRAY['/images/digital-media/digital_signage/17-1-controller_PC.jpg', '/images/digital-media/digital_signage/17-2_controller_HD.jpg', '/images/digital-media/digital_signage/17-3-controller_FHD.jpg', '/images/digital-media/digital_signage/17-4_controller_FHD.jpg'],
 'LED 디스플레이 컨트롤러', 'LED Controller Series', 'HD용', '주식회사 시스메이트', 'N/A',
 'N/A', 'N/A', 'N/A',
 '컨트롤러 HD용',
 'LED 디스플레이 제어',
 'N/A', 'N/A', '상담문의',
 'LED 컨트롤러',
 'LED 디스플레이용 컨트롤러 제품들입니다.',
 NULL, '02-711-3737', 161, true),

('led-controller-mctrl600', 'LED 컨트롤러 MCTRL600', '/images/digital-media/digital_signage/17-3-controller_FHD.jpg',
 ARRAY['/images/digital-media/digital_signage/17-1-controller_PC.jpg', '/images/digital-media/digital_signage/17-2_controller_HD.jpg', '/images/digital-media/digital_signage/17-3-controller_FHD.jpg', '/images/digital-media/digital_signage/17-4_controller_FHD.jpg'],
 'LED 디스플레이 컨트롤러', 'LED Controller Series', 'MCTRL600', '주식회사 시스메이트', 'N/A',
 'N/A', 'N/A', 'N/A',
 '컨트롤러 FHD용',
 'LED 디스플레이 제어',
 'N/A', 'N/A', '상담문의',
 'LED 컨트롤러',
 'LED 디스플레이용 컨트롤러 제품들입니다.',
 NULL, '02-711-3737', 162, true),

('led-controller-mctrl660', 'LED 컨트롤러 MCTRL 660 PRO', '/images/digital-media/digital_signage/17-4_controller_FHD.jpg',
 ARRAY['/images/digital-media/digital_signage/17-1-controller_PC.jpg', '/images/digital-media/digital_signage/17-2_controller_HD.jpg', '/images/digital-media/digital_signage/17-3-controller_FHD.jpg', '/images/digital-media/digital_signage/17-4_controller_FHD.jpg'],
 'LED 디스플레이 컨트롤러', 'LED Controller Series', 'MCTRL 660 PRO', '주식회사 시스메이트', 'N/A',
 'N/A', 'N/A', 'N/A',
 '컨트롤러 FHD용',
 'LED 디스플레이 제어',
 'N/A', 'N/A', '상담문의',
 'LED 컨트롤러',
 'LED 디스플레이용 컨트롤러 제품들입니다.',
 NULL, '02-711-3737', 163, true),

-- LED 디스플레이 설치비
('led-installation-service', 'LED 디스플레이 설치 서비스', '/images/digital-media/digital_signage/18_LEDdisplay_installation.png',
 ARRAY['/images/digital-media/digital_signage/18_LEDdisplay_installation.png'],
 'LED 디스플레이 설치비', 'LED Installation Series', 'LED 설치 서비스', '주식회사 시스메이트', '32인치 ~ 98인치',
 'N/A', 'N/A', 'N/A',
 '특수시공 분류: 벽면노출, 벽면매립, 스탠드 거치, 이동형 스탠드, 천정시공 등',
 'LED 디스플레이 설치',
 '시공 가용 인치: 32인치 ~ 98인치 및, 그 외 특수규격 시공 가능', 'N/A', '상담문의',
 'LED 설치 서비스',
 'LED 디스플레이 설치 서비스입니다.',
 NULL, '02-711-3737', 170, true),

-- 더 갤러리 - QH Series (추가)
('the-gallery-qh43', '더 갤러리 QH43F', '/images/digital-media/digital_signage/10_theGallery.png',
 ARRAY['/images/digital-media/digital_signage/10_theGallery.png'],
 '더 갤러리', 'QH Series', 'QH43F_WTE', '삼성전자', '43인치',
 '978.8 x 567 x 37', '3,840 x 2,160', '500cd/m²',
 'USB INPUT 제어 / 매직인포 네트워크 솔루션',
 '광고, 홍보, 메뉴보드, 캠페인 등의 미디어 콘텐츠 송출',
 '벽면설치, 매립설치, 천정설치 등', '200 x 200', '상담문의',
 '액자형 사이니지, 프레임 색상: 화이트, 옵션 사항: 명화 콘텐츠',
 '액자형 사이니지로 명화 콘텐츠를 지원하는 고품질 디스플레이입니다.',
 NULL, '02-711-3737', 88, true),

('the-gallery-qh50', '더 갤러리 QH50F', '/images/digital-media/digital_signage/10_theGallery.png',
 ARRAY['/images/digital-media/digital_signage/10_theGallery.png'],
 '더 갤러리', 'QH Series', 'QH50F_WTE', '삼성전자', '50인치',
 '1133.3 x 654 x 37', '3,840 x 2,160', '500cd/m²',
 'USB INPUT 제어 / 매직인포 네트워크 솔루션',
 '광고, 홍보, 메뉴보드, 캠페인 등의 미디어 콘텐츠 송출',
 '벽면설치, 매립설치, 천정설치 등', '200 x 200', '상담문의',
 '액자형 사이니지, 프레임 색상: 화이트, 옵션 사항: 명화 콘텐츠',
 '액자형 사이니지로 명화 콘텐츠를 지원하는 고품질 디스플레이입니다.',
 NULL, '02-711-3737', 171, true),

('the-gallery-qh55', '더 갤러리 QH55F', '/images/digital-media/digital_signage/10_theGallery.png',
 ARRAY['/images/digital-media/digital_signage/10_theGallery.png'],
 '더 갤러리', 'QH Series', 'QH55F_WTE', '삼성전자', '55인치',
 '1247.2 x 718 x 37', '3,840 x 2,160', '500cd/m²',
 'USB INPUT 제어 / 매직인포 네트워크 솔루션',
 '광고, 홍보, 메뉴보드, 캠페인 등의 미디어 콘텐츠 송출',
 '벽면설치, 매립설치, 천정설치 등', '200 x 200', '상담문의',
 '액자형 사이니지, 프레임 색상: 화이트, 옵션 사항: 명화 콘텐츠',
 '액자형 사이니지로 명화 콘텐츠를 지원하는 고품질 디스플레이입니다.',
 NULL, '02-711-3737', 172, true),

('the-gallery-qh65', '더 갤러리 QH65F', '/images/digital-media/digital_signage/10_theGallery.png',
 ARRAY['/images/digital-media/digital_signage/10_theGallery.png'],
 '더 갤러리', 'QH Series', 'QH65F_WTE', '삼성전자', '65인치',
 '1466 x 841 x 37', '3,840 x 2,160', '500cd/m²',
 'USB INPUT 제어 / 매직인포 네트워크 솔루션',
 '광고, 홍보, 메뉴보드, 캠페인 등의 미디어 콘텐츠 송출',
 '벽면설치, 매립설치, 천정설치 등', '200 x 200', '상담문의',
 '액자형 사이니지, 프레임 색상: 화이트, 옵션 사항: 명화 콘텐츠',
 '액자형 사이니지로 명화 콘텐츠를 지원하는 고품질 디스플레이입니다.',
 NULL, '02-711-3737', 173, true);

-- 완료 메시지
SELECT 'Digital products data inserted successfully!' as status;

