-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.bank_info (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  region_gu_id uuid,
  display_type_id uuid,
  bank_name character varying,
  account_number character varying,
  depositor character varying,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT bank_info_pkey PRIMARY KEY (id),
  CONSTRAINT bank_info_region_gu_id_fkey FOREIGN KEY (region_gu_id) REFERENCES public.region_gu(id),
  CONSTRAINT bank_info_display_type_id_fkey FOREIGN KEY (display_type_id) REFERENCES public.display_types(id)
);
CREATE TABLE public.banner_panel_details (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  panel_info_id uuid NOT NULL UNIQUE,
  is_for_admin boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT banner_panel_details_pkey PRIMARY KEY (id),
  CONSTRAINT banner_panel_details_panel_info_id_fkey FOREIGN KEY (panel_info_id) REFERENCES public.panel_info(id)
);
CREATE TABLE public.banner_slot_info (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  panel_info_id uuid NOT NULL,
  slot_number numeric NOT NULL,
  slot_name text,
  max_width numeric,
  max_height numeric,
  total_price numeric CHECK (total_price >= 0::numeric),
  tax_price numeric CHECK (tax_price >= 0::numeric),
  banner_type USER-DEFINED,
  price_unit USER-DEFINED DEFAULT '15 days'::price_unit_enum,
  is_premium boolean DEFAULT false,
  panel_slot_status USER-DEFINED DEFAULT 'available'::panel_slot_status_enum,
  notes text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  road_usage_fee numeric CHECK (road_usage_fee >= 0::numeric),
  advertising_fee numeric CHECK (advertising_fee >= 0::numeric),
  CONSTRAINT banner_slot_info_pkey PRIMARY KEY (id),
  CONSTRAINT banner_slot_info_panel_info_id_fkey FOREIGN KEY (panel_info_id) REFERENCES public.panel_info(id)
);
CREATE TABLE public.banner_slot_price_policy (
  id uuid NOT NULL,
  banner_slot_info_id uuid NOT NULL,
  price_usage_type USER-DEFINED NOT NULL,
  tax_price integer NOT NULL DEFAULT 0,
  road_usage_fee integer NOT NULL DEFAULT 0,
  advertising_fee integer NOT NULL DEFAULT 0,
  total_price integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT banner_slot_price_policy_pkey PRIMARY KEY (id),
  CONSTRAINT banner_slot_price_policy_banner_slot_info_id_fkey FOREIGN KEY (banner_slot_info_id) REFERENCES public.banner_slot_info(id)
);
CREATE TABLE public.customer_inquiries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_auth_id uuid NOT NULL,
  title text NOT NULL,
  content text NOT NULL,
  product_name text,
  inquiry_status USER-DEFINED DEFAULT 'pending'::inquiry_status_enum,
  answer_content text,
  answer_admin_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  answered_at timestamp with time zone,
  closed_at timestamp with time zone,
  CONSTRAINT customer_inquiries_pkey PRIMARY KEY (id)
);
CREATE TABLE public.customer_service (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title character varying NOT NULL,
  content text NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying,
  answer text,
  answered_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customer_service_pkey PRIMARY KEY (id),
  CONSTRAINT customer_service_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_auth(id)
);
CREATE TABLE public.display_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name USER-DEFINED NOT NULL,
  description text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT display_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.homepage_contents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  homepage_menu_type uuid,
  title text NOT NULL,
  subtitle text NOT NULL,
  description text,
  description_list ARRAY,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  main_image_url text,
  CONSTRAINT homepage_contents_pkey PRIMARY KEY (id),
  CONSTRAINT homepage_contents_homepage_menu_type_fkey FOREIGN KEY (homepage_menu_type) REFERENCES public.homepage_menu_types(id)
);
CREATE TABLE public.homepage_menu_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name USER-DEFINED NOT NULL,
  description text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  CONSTRAINT homepage_menu_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.homepage_notice (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  content text NOT NULL,
  is_active boolean DEFAULT true,
  priority USER-DEFINED DEFAULT 'normal'::notice_priority_enum,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT homepage_notice_pkey PRIMARY KEY (id)
);
CREATE TABLE public.led_panel_details (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  panel_info_id uuid NOT NULL UNIQUE,
  exposure_count integer CHECK (exposure_count >= 0),
  panel_width integer CHECK (panel_width > 0),
  panel_height integer CHECK (panel_height > 0),
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  max_banners integer DEFAULT 20 CHECK (max_banners > 0),
  CONSTRAINT led_panel_details_pkey PRIMARY KEY (id),
  CONSTRAINT led_panel_details_panel_info_id_fkey FOREIGN KEY (panel_info_id) REFERENCES public.panel_info(id)
);
CREATE TABLE public.led_slot_info (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  panel_info_id uuid NOT NULL,
  slot_name text,
  slot_width_px integer,
  slot_height_px integer,
  position_x integer DEFAULT 0,
  position_y integer DEFAULT 0,
  total_price numeric CHECK (total_price >= 0::numeric),
  tax_price numeric CHECK (tax_price >= 0::numeric),
  price_unit USER-DEFINED DEFAULT '15 days'::price_unit_enum,
  is_premium boolean DEFAULT false,
  panel_slot_status USER-DEFINED DEFAULT 'available'::panel_slot_status_enum,
  notes text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  advertising_fee numeric CHECK (advertising_fee >= 0::numeric),
  road_usage_fee numeric CHECK (road_usage_fee >= 0::numeric),
  administrative_fee numeric CHECK (administrative_fee >= 0::numeric),
  slot_number integer NOT NULL CHECK (slot_number >= 1 AND slot_number <= 30),
  first_half_closure_quantity integer DEFAULT 0,
  second_half_closure_quantity integer DEFAULT 0,
  CONSTRAINT led_slot_info_pkey PRIMARY KEY (id),
  CONSTRAINT led_slot_info_panel_info_id_fkey FOREIGN KEY (panel_info_id) REFERENCES public.panel_info(id)
);
CREATE TABLE public.notice_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  sub_name character varying NOT NULL,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone,
  CONSTRAINT notice_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.order_details (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  slot_order_quantity integer,
  display_start_date date,
  display_end_date date,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  half_period text CHECK (half_period = ANY (ARRAY['first_half'::text, 'second_half'::text])),
  panel_info_id uuid,
  panel_slot_usage_id uuid,
  CONSTRAINT order_details_pkey PRIMARY KEY (id),
  CONSTRAINT order_details_panel_slot_usage_id_fkey FOREIGN KEY (panel_slot_usage_id) REFERENCES public.panel_slot_usage(id),
  CONSTRAINT order_details_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_details_panel_info_id_fkey FOREIGN KEY (panel_info_id) REFERENCES public.panel_info(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  panel_slot_snapshot jsonb,
  total_price numeric CHECK (total_price >= 0::numeric),
  depositor_name text,
  deposit_date date,
  is_paid boolean DEFAULT false,
  is_checked boolean DEFAULT false,
  invoice_issued_at date,
  invoice_file text,
  payment_method text,
  is_received_order boolean DEFAULT false,
  is_received_paymenet boolean DEFAULT false,
  is_draft_sent boolean DEFAULT false,
  is_draft_received boolean DEFAULT false,
  is_address_verified boolean DEFAULT false,
  is_draft_verified boolean,
  display_location text,
  received_payment_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  auth_user_id uuid,
  half_period text CHECK (half_period = ANY (ARRAY['first_half'::text, 'second_half'::text])),
  user_profile_id uuid,
  user_auth_id uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
  year_month character varying NOT NULL DEFAULT '2025-06'::character varying,
  order_number character varying,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_user_profile_id_fkey FOREIGN KEY (user_profile_id) REFERENCES public.user_profiles(id),
  CONSTRAINT orders_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES public.user_auth(id)
);
CREATE TABLE public.panel_guideline (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  display_category_id uuid,
  notes text,
  order_period text,
  order_method text,
  account_info text,
  main_notice text,
  warning_notice text,
  show_warning boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  image_url ARRAY,
  region_gu_id uuid,
  guideline_type USER-DEFINED,
  CONSTRAINT panel_guideline_pkey PRIMARY KEY (id),
  CONSTRAINT panel_guideline_display_category_id_fkey FOREIGN KEY (display_category_id) REFERENCES public.display_types(id)
);
CREATE TABLE public.panel_info (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  display_type_id uuid,
  post_code text UNIQUE,
  region_gu_id uuid,
  region_dong_id uuid,
  nickname text NOT NULL,
  address text,
  photo_url text,
  location_url text,
  map_url text,
  latitude numeric,
  longitude numeric,
  panel_status USER-DEFINED DEFAULT 'active'::panel_status_enum,
  maintenance_notes text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  panel_code smallint CHECK (panel_code >= 1 AND panel_code <= 100),
  panel_type USER-DEFINED,
  max_banner integer DEFAULT 1,
  first_half_closure_quantity integer DEFAULT 0,
  second_half_closure_quantity integer DEFAULT 0,
  CONSTRAINT panel_info_pkey PRIMARY KEY (id),
  CONSTRAINT panel_info_display_type_id_fkey FOREIGN KEY (display_type_id) REFERENCES public.display_types(id),
  CONSTRAINT panel_info_region_gu_id_fkey FOREIGN KEY (region_gu_id) REFERENCES public.region_gu(id),
  CONSTRAINT panel_info_region_dong_id_fkey FOREIGN KEY (region_dong_id) REFERENCES public.region_dong(id)
);
CREATE TABLE public.panel_popup_notices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  display_category_id uuid,
  title text,
  hide_oneday boolean DEFAULT false,
  content json,
  image_url text,
  start_date date,
  end_date date,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  region_gu_id uuid,
  notice_categories_id uuid,
  CONSTRAINT panel_popup_notices_pkey PRIMARY KEY (id),
  CONSTRAINT panel_popup_notices_display_category_id_fkey FOREIGN KEY (display_category_id) REFERENCES public.display_types(id),
  CONSTRAINT panel_popup_notices_region_gu_id_fkey FOREIGN KEY (region_gu_id) REFERENCES public.region_gu(id)
);
CREATE TABLE public.panel_slot_usage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  display_type_id uuid,
  panel_info_id uuid,
  slot_number integer,
  usage_type text,
  attach_date_from date,
  unit_price numeric CHECK (unit_price >= 0::numeric),
  is_active boolean DEFAULT true,
  is_closed boolean DEFAULT false,
  banner_type USER-DEFINED NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  banner_slot_info_id uuid,
  order_details_id uuid,
  CONSTRAINT panel_slot_usage_pkey PRIMARY KEY (id),
  CONSTRAINT panel_slot_usage_order_details_id_fkey FOREIGN KEY (order_details_id) REFERENCES public.order_details(id),
  CONSTRAINT panel_slot_usage_display_type_id_fkey FOREIGN KEY (display_type_id) REFERENCES public.display_types(id),
  CONSTRAINT panel_slot_usage_panel_info_id_fkey FOREIGN KEY (panel_info_id) REFERENCES public.panel_info(id),
  CONSTRAINT panel_slot_usage_banner_slot_info_id_fkey FOREIGN KEY (banner_slot_info_id) REFERENCES public.banner_slot_info(id)
);
CREATE TABLE public.region_dong (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  district_code text NOT NULL,
  name character varying NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT region_dong_pkey PRIMARY KEY (id),
  CONSTRAINT region_dong_district_code_fkey FOREIGN KEY (district_code) REFERENCES public.region_gu(code)
);
CREATE TABLE public.region_gu (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name character varying NOT NULL,
  logo_image_url text,
  bank_info text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  phone_number text,
  is_active boolean DEFAULT false,
  CONSTRAINT region_gu_pkey PRIMARY KEY (id)
);
CREATE TABLE public.region_gu_display_periods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  display_type_id uuid,
  region_gu_id uuid,
  first_half_from date,
  first_half_to date,
  first_half_closure_quantity integer DEFAULT 0,
  second_half_from date,
  second_half_to date,
  second_half_closure_quantity integer DEFAULT 0,
  next_first_half_from date,
  next_first_half_to date,
  next_first_half_closure_quantity integer DEFAULT 0,
  next_second_half_from date,
  next_second_half_to date,
  next_second_half_closure_quantity integer DEFAULT 0,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  year_month character varying NOT NULL DEFAULT '2025-06'::character varying,
  CONSTRAINT region_gu_display_periods_pkey PRIMARY KEY (id),
  CONSTRAINT region_gu_display_periods_display_type_id_fkey FOREIGN KEY (display_type_id) REFERENCES public.display_types(id),
  CONSTRAINT region_gu_display_periods_region_gu_id_fkey FOREIGN KEY (region_gu_id) REFERENCES public.region_gu(id)
);
CREATE TABLE public.region_gu_guideline (
  id uuid NOT NULL,
  region_gu_id uuid,
  display_type USER-DEFINED NOT NULL,
  category USER-DEFINED DEFAULT 'default'::guideline_category_enum,
  title text,
  description text,
  image_urls ARRAY,
  content_json jsonb,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT region_gu_guideline_pkey PRIMARY KEY (id),
  CONSTRAINT region_gu_guideline_region_gu_id_fkey FOREIGN KEY (region_gu_id) REFERENCES public.region_gu(id)
);
CREATE TABLE public.user_auth (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  username character varying NOT NULL UNIQUE,
  email character varying NOT NULL UNIQUE,
  password character varying NOT NULL,
  name character varying NOT NULL,
  phone character varying,
  is_verified boolean DEFAULT false,
  is_active boolean DEFAULT true,
  terms_agreed boolean DEFAULT false,
  privacy_agreed boolean DEFAULT false,
  collection_agreed boolean DEFAULT false,
  third_party_agreed boolean DEFAULT false,
  agreed_at timestamp with time zone,
  last_login timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_auth_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_auth_id uuid,
  profile_title text NOT NULL,
  company_name text,
  business_registration_number text,
  phone text NOT NULL,
  email text NOT NULL,
  contact_person_name text NOT NULL,
  fax_number text,
  is_default boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  is_public_institution boolean DEFAULT false,
  is_company boolean DEFAULT false,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_user_auth_id_fkey FOREIGN KEY (user_auth_id) REFERENCES public.user_auth(id)
);